### ISSUE TITLE
Support Option<SourceError> and Option<Backtrace>

### ISSUE THREAD

**Issue by mathstuf** [dtolnay/thiserror#1]
This should be possible:

```rust
enum MyErr {
    OptSource {
        #[source]
        source: Option<io::Error>,
    },
}
```

**Comment by dtolnay** [comment]
Thanks, I agree. I will get to this in the next few days if someone doesn't beat me with a PR.

We'd probably want `Option<Backtrace>` too.

**Comment by mathstuf** [comment]
I took a quick look. It seems that it is done on the first entry found using the `#[source]` macro (meaning that duplicate `#[source]` entries are silently ignored). I don't know if it's better to add a new `#[opt_source]` attribute or try and divine the `Option` out from the literal type given. A new attribute seems more likely to be implementable.

There should probably also be a `#[backtrace]` attribute in case some type aliasing shenanigans is going on (it seems that it just wants the last path component to be the literal `Backtrace` at the moment). This probably means that `#[opt_backtrace]` would be the way to go there.
