### ISSUE TITLE
#[error(concat!("foo ", $param))] silently ignored

### ISSUE THREAD

**Issue by Kixunil** [dtolnay/thiserror#105]
Consider this code:

```rust
macro_rules! error_type {
    ($name:ident, $what:expr) => {
        #[derive(Debug, thiserror::Error)]
        // This doesn't work
        #[error(concat!("invalid ", $what))]
        // This does work
        // #[error("invalid")]
        struct Error;
    }
}

error_type!(Error, "foo");

fn main() {
    println!("error: {}", Error);
}
```

The compiler complains about `Error` not implementing `Display` but has no problem with `concat!()` being in the attribute. My understanding is that the macro call tokens are passed into `thiserror` which then ignores it instead of complaining or implementing `Display`.

I'd very much like to see `thiserror` supporting `concat!` as it makes creating new error types much easier. If that's not possible, then there should be a proper error message explaining it.

Since `thiserror` is not available in playground I've created a [repository demonstrating this bug](https://github.com/Kixunil/broken_thiserror) for your convenience.

**Comment by dtolnay** [comment]
I am not able to reproduce this. I cloned the repo you gave and ran cargo check, but it shows the attribute containing concat as a parse error, not silently ignored.

Could you provide the Rust toolchain version and target on which you're observing it silently ignored?

<pre>
$  <b>cargo check</b>

error: expected literal
  --> src/main.rs:5:17
   |
5  |         #[error(concat!("invalid ", $what))]
   |                 ^^^^^^
...
12 | error_type!(Error, "foo");
   | -------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
</pre>

**Comment by Kixunil** [comment]
Oh, it happens in version 1.41.1, didn't occur to me that this could be Rsut-version-dependent.

Since the error is from `thiserror`, I guess it should be possible to make it work. Would you agree to allowing `concat!` (and possibly other macros)?

**Comment by dtolnay** [comment]
I think it should be sufficient that we support fmt expressions already. `#[error("invalid {}", $what)]`

**Comment by Kixunil** [comment]
Ah, didn't notice that, that's sufficient and I don't mind the small overhead.

**Comment by Kixunil** [comment]
Hmm, wanted to try, but I get `error: expected expression, found $`

It looks like `$what` is not expanded before calling the proc macro.
