### ISSUE TITLE
Support using error message from source

### ISSUE THREAD

**Issue by MOZGIII** [dtolnay/thiserror#12]
I have a very simple enum that just wraps all other error types:

```rust
#[derive(Debug)]
pub enum SomeParseFromEnvError {
    InvalidLogFormat(ParseFromEnvError<InvalidLogFormat>),
    InvalidBool(ParseFromEnvError<ParseBoolError>),
    InvalidInfallible(ParseFromEnvError<Infallible>),
}
```

The `Display` implementation I have doesn't do anything fancy - it just relies the `fmt` directly to the wrapped value:

```rust
impl std::fmt::Display for SomeParseFromEnvError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SomeParseFromEnvError::InvalidLogFormat(err) => err.fmt(f),
            SomeParseFromEnvError::InvalidBool(err) => err.fmt(f),
            SomeParseFromEnvError::InvalidInfallible(err) => err.fmt(f),
        }
    }
}
```

I need a simple way to derive the same behavior.
Annotation every field with `#[error("{0})]` is an option that I currently have to use, but it doesn't expand to the same code I write manually.
Also, `#[error("{0})]` above every field doesn't look good :smile:

**Comment by dtolnay** [comment]
I would accept a PR to treat:

```rust
#[derive(Debug)]
#[error(...)]
pub enum SomeParseFromEnvError {
    InvalidLogFormat(ParseFromEnvError<InvalidLogFormat>),
    InvalidBool(ParseFromEnvError<ParseBoolError>),
    InvalidInfallible(ParseFromEnvError<Infallible>),
}
```

as equivalent to:

```rust
#[derive(Debug)]
pub enum SomeParseFromEnvError {
    #[error(...)]
    InvalidLogFormat(ParseFromEnvError<InvalidLogFormat>),
    #[error(...)]
    InvalidBool(ParseFromEnvError<ParseBoolError>),
    #[error(...)]
    InvalidInfallible(ParseFromEnvError<Infallible>),
}
```

Would that work for your use case? You would put `#[error("{0}")]` once at the top of the enum.

<br>

> it doesn't expand to the same code I write manually.

Thanks, I filed #13 to track this separately.

**Comment by MOZGIII** [comment]
I guess `#[error("{0}")]` is the problem, how about we use `#[error_proxy_to_source]` or sth?

**Comment by dtolnay** [comment]
You can alternatively write `#[error("{}", .0)]` if that's less bothersome.

I think I wouldn't consider this annoying enough to introduce a new `#[error_proxy_to_source]` attribute that does the same thing.

**Comment by dtolnay** [comment]
Closing in favor of #18.
