### ISSUE TITLE
Request: Add Method to Return Error Enum Variant Name

### ISSUE THREAD

**Issue by theory** [dtolnay/thiserror#120]
I wrote a macro to use in my tests, so that I can verify that an error is of the proper variant and stringification. It looks like this:

``` rust
macro_rules! assert_err {
    ($x:expr, $e:path, $m:expr, $($f:tt)+) => {
        if let Err(e) = $x {
            if let $e(..) = e {
                assert_eq!($m, e.to_string(), $($f)+);
            } else {
                // XXX Figure out how to get the variant name of e.
                panic!(r#"assertion failed (error doesn't match pattern):
error: `{}`,
pattern: `{}: {}`"#, e, stringify!($e), format_args!($($f)+))
            }
        } else {
            panic!(r#"assertion failed (value is not an error)`: {}"#, format_args!($($f)+));
        }
    };
}
```

I use it like this:

``` rust
assert_err!(
    Foo::new(cfg), // returns Result
    Error::InvalidConfig, // Expected error
    "Invalid config: Must have blorf of 10 or more", // Expected string
    "Should have config error for too few blorfs",
);
```

I'm reasonably happy with this, as it lets me test all variants regardless of their fields. But one thing I'd like to improve is the ability to print the name of the variant if it doesn't match, as mentioned in the `XXX` comment. Is there a way to define a method on a thiserror-defined error that would return a string (or &str) with the variant name? If not, would it make sense to add such a feature, perhaps with an option to turn it on only for certain configs, like `#[cfg(test)]`?

**Comment by dtolnay** [comment]
I would prefer not to build this into thiserror, but it seems reasonable for someone to create as a separate macro.

**Comment by theory** [comment]
I think my description here might have obfuscated the actual request, which is:

> Is there a way to define a method on a thiserror-defined error that would return a string (or &str) with the variant name?  If not, would it make sense to add such a feature, perhaps with an option to turn it on only for certain configs, like #[cfg(test)]?

I was not able to figure out how to do this in a macro, but maybe I just missed something.

**Comment by evbo** [comment]
You can simply have your thiserror `enum` derive strum's `AsRefStr`
