### ISSUE TITLE
Support for Termination trait?

### ISSUE THREAD

**Issue by mintyc** [dtolnay/thiserror#122]
Allow support for using the generated error type with doctest output requiring a fn report() -> i32 addition

Motivation at https://github.com/rust-lang/rfcs/blob/master/text/1937-ques-in-main.md
https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.html

**Comment by dtolnay** [comment]
This is already supported completely independent of thiserror due to Result's Termination impls in the standard library. Any error type with just a Debug impl can be used with `?` in doc tests, whether or not you also derive `Error`.
