### ISSUE TITLE
How to deal with multiple same source types?

### ISSUE THREAD

**Issue by FooBarWidget** [dtolnay/thiserror#123]
I'm migrating from the now-unmaintained [failure](https://github.com/rust-lang-nursery/failure) crate and I'm trying to figure out how to deal with multiple same source types.

Given this example code...

~~~rust
use core::num::ParseIntError;
use thiserror::Error;

#[derive(Error, Debug)]
enum MyError {
    #[error("Error A: {0}")]
    ErrorA(#[from] ParseIntError),
    
    #[error("Error B: {0}")]
    ErrorB(#[from] ParseIntError),
}

fn main() {
    let parse_err = match String::from("abc").parse::<isize>() {
        Ok(_) => panic!("Error expected"),
        Err(e) => e,
    };
    println!("Error = {}", MyError::ErrorA(parse_err));
}
~~~

I get:

~~~
cannot derive From because another variant has the same source type
~~~

What's the best way to deal with this? ErrorA and ErrorB have different meanings even though they both have ParseIntError as source. For example, ErrorA could say "error parsing age" and ErrorB could say "error parsing social security number".

**Comment by wonkodv** [comment]
remove the `#[from]`

**Comment by FooBarWidget** [comment]
I got it, I'm supposed to use `#[source]` instead of `#[from]`.

Thanks!
