### ISSUE TITLE
const errors

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dtolnay/thiserror#125]
My erros are such:
```
    /// Required liquidity token ab is more than max
    #[error("Required liquidity token AB is more than max")]
    RequiredLiquidityTokenABIsMoreThanMax,
```
All errors are of static text, numbered (To, FromPrimitive derives) and error /// comment is the same as an error message. Use for very low-level stuff. Numbers on the bus-wire, but mapped back to string on the client or in logs. 

Question: is it possible for special handling so that macro eats /// comment as message for error to_string, and may be have as to_string_ref (as strum does).

thanks

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate (but it would probably be reasonable for a different crate to do).
