### ISSUE TITLE
How can this work with a Vec<Error>

### ISSUE THREAD

**Issue by Bajix** [dtolnay/thiserror#126]
As far as I can tell there's no way to make this work:
```
use thiserror::Error;
use async_graphql::ServerError;

#[derive(Error, Debug)]
pub enum DataError {
  #[error("{0:?}")]
  GraphQLError(#[from] Vec<ServerError>)
}
```

**Comment by dtolnay** [comment]
That's right, this crate is specifically for single errors. For working with multiple simultaneous errors, you would want to find another approach. I don't have crate recommendations.
