### ISSUE TITLE
PartialEq and tests

### ISSUE THREAD

**Issue by bonega** [dtolnay/thiserror#127]
Often I want to assert that some Result is equal to an Error variant.

```rust
  #[test]
    fn test_no_slot() {
        let slot_config = SlotConfig::new(0, 0, 0, 0, 0);
        assert_eq!(BackedUpError::NoSlot, slot_config.err().unwrap());
    }
```

This works fine if I just add `PartialEq` to my Error Enum.
Problem is if I want to include an external error that is not `PartialEq`.
Example:
```Rust 
#[derive(Error, Debug, PartialEq)]
pub enum BackedUpError {
    #[error("Couldn't open directory {path}")]
    ReadDirError { source: io::Error, path: PathBuf },
    #[error("At least one slot must be configured")]
    NoSlot
}
```

In this example `ReadDirError` cannot implement `PartialEq`.
The solution I went with was to make a newtype from `io::Error` and implement `PartialEq` for it.

```rust
#[derive(Debug, Error)]
pub struct IoError(io::Error);

impl Display for IoError {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result<(), std::fmt::Error> {
        self.0.fmt(f)
    }
}

impl PartialEq for IoError {
    fn eq(&self, other: &Self) -> bool {
        self == other
    }
}
```

Is there anything in `thiserror` to avoid the `PartialEq`/`Display` boilerplate?

**Comment by dtolnay** [comment]
This sounds almost entirely unrelated to errors &mdash; you see the same thing regardless of whether `BackedUpError` uses thiserror or even implements Error at all.

```rust
use std::io;
use std::path::PathBuf;

#[derive(Debug, PartialEq)]
pub enum BackedUpError {
    ReadDirError { source: io::Error, path: PathBuf },
    NoSlot
}
```

```console
error[E0369]: binary operation `==` cannot be applied to type `std::io::Error`
 --> src/lib.rs:6:20
  |
6 |     ReadDirError { source: io::Error, path: PathBuf },
  |                    ^^^^^^^^^^^^^^^^^
```

Thiserror does not address this.

**Comment by nyurik** [comment]
@dtolnay you are right that this is mostly unrelated to errors, and yet it is a very common scenario - enough so that stackoveflow [questions](https://stackoverflow.com/questions/57234140/how-to-assert-io-errors-in-rust) keep popping up.  Should there be some sort of a guide/documentation links for this issue?
