### ISSUE TITLE
Prefix string for enum types

### ISSUE THREAD

**Issue by rmccampbell** [dtolnay/thiserror#128]
For many error enums you might want a common message to be printed before the individual message for each variant. A possible syntax could be:
```rust
#[derive(Debug, Error)]
#[error(prefix="Invalid syntax: ")]
enum ParseError {
    #[error("unmatched left bracket")]
    UnmatchedLeftBracket,
    #[error("unmatched right bracket")]
    UnmatchedRightBracket,
}
```
This would return "Invalid syntax: unmatched left bracket" for the display of the first case.

**Comment by dtolnay** [comment]
I would prefer not to build this into this library -- but it would be fine if someone wanted to maintain a fork for this.
