### ISSUE TITLE
Generic trait bounds and the "?" operator

### ISSUE THREAD

**Issue by vikigenius** [dtolnay/thiserror#129]
This is a followup to this stackoverflow question: https://stackoverflow.com/questions/67352894/rust-error-conversion-for-generic-fromstr-unwrap-errors-out-with-unsatisfied-tr/67354940#67354940

I have the following error defined

```rust
use thiserror::Error;

/// ParseTreeError enumerates all possible errors returned by this library.
#[derive(Error, Debug)]
pub enum ParseTreeError {
    /// Represents an empty source. For example, an empty text file being given
    /// as input to `count_words()`.
    #[error("Source contains no data")]
    EmptySource,

    /// Represents a failure to read from input.
    #[error("Read error")]
    ReadError,
}
```

Now consider the following code from the SO Answer (slightly changed)

```rust
fn test_parse<T>() -> Result<(), ParseTreeError>
where
    T: FromStr,
    <T as FromStr>::Err: fmt::Debug,             // <<<<
{
    let mut val = T::from_str("5").unwrap();
    Ok(())
}
```

As suggested by the answer it seems like to allow the usage of ? operator I would need to implement `From<<T as FromStr>::Err>`

What would be the correct way of doing this with thiserror? Changing ParseTreeError to generic and using `#[from]` seems to be causing issues with conflicting trait implementations.

**Comment by dtolnay** [comment]
Hi @vikigenius, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This crate is fairly widely used so lots of people will have experience to help you out.
