### ISSUE TITLE
Optimize "{0}" and "{var}" to not require `write!`

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/thiserror#13]
#12 called out that the generated code from `"{0}"` is messier than just a `Display::fmt(_0, formatter)`. I don't know why `write!` doesn't handle this case better, but we might as well do it in thiserror.

```rust
#[derive(Error, Debug)]
pub enum ParseFromEnvError {
    #[error("{0}")]
    InvalidLogFormat(io::Error),
}
```

^ Should expand the Display impl to: 

```diff
  match self {
-     ParseFromEnvError::InvalidLogFormat(_0) => write!(formatter, "{}", _0),
+     ParseFromEnvError::InvalidLogFormat(_0) => Display::fmt(_0, formatter),
  }
```

@MOZGIII

**Comment by MOZGIII** [comment]
This definetly does the right thing. I still don't like `#[error("{0}")]` though. How about adding `#[error_proxy]` or something of that sort?
