### ISSUE TITLE
I wish there was a feature to allow use of the backtrace crate rather than std::backtrace

### ISSUE THREAD

**Issue by dcormier** [dtolnay/thiserror#130]
To allow errors to have backtraces without having to use a nightly toolchain, I wish this crate had a feature to use the [`backtrace` crate](https://crates.io/crates/backtrace) in place of [`std::backtrace`](https://doc.rust-lang.org/std/backtrace/index.html).

**Comment by LukeMauldin** [comment]
I agree, this is important to our usage too.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate, since it is specifically for deriving std::error::Error. It would be reasonable for someone else to maintain a derive macro that deals with non-std backtraces.

**Comment by john01dav** [comment]
It would be better to have this crate only attempt to do anything with backtraces if on nightly. As it is right now, I can't even have a field of type `backtrace::Backtrace` on my errors, without any integration, on stable as `thiserror` tries to use it for a nightly backtrace which causes errors.

**Comment by dtolnay** [comment]
You need to use a different crate. I am not interested in supporting that case in this crate.
