### ISSUE TITLE
Easy mechanism to associate error codes with errors

### ISSUE THREAD

**Issue by nwalfield** [dtolnay/thiserror#133]
First, thanks for the great library.

I'm working on some Rust code that *sometimes* needs to return errors to C code.  The C code defines about 100 error codes (`#define ERROR_FOO 0x10` `#define ERROR_BAR 0x11`).  In Rust, I have something that looks like:

```
#[derive(Error, Debug)]
pub enum DataStoreError {
    #[error("foo happened: {0}")]
    Foo(String),
    #[error("bar happened: {0}")]
    Bar(String),
}
```

It would be nice, if I could add an annotation of the sort: `#[into(usize, 0x10)]` for each of the variants and thiserror would then automatically generate a `From` (or `TryFrom`) implementation.  Instead, I now have a big function with a `match` to convert the rich errors to simple error codes.

**Comment by dtolnay** [comment]
I would prefer not to build anything for this into this crate. But your suggestion sounds like something that could readily be handled by a separate crate.

**Comment by nwalfield** [comment]
In case someone has a similar issue: I've added this functionality to the [enumber crate](https://github.com/kinnison/enumber/commit/47f70b990dd87ad153e05510536046171148c60c).
