### ISSUE TITLE
Allowing nonstandard_macro_braces runs afoul of unknown_clippy_lints

### ISSUE THREAD

**Issue by damianwadley** [dtolnay/thiserror#140]
nonstandard_macro_braces was added to clippy [recently](https://github.com/rust-lang/rust-clippy/commit/723f515b6006706b88d22c8edb05330df6365a63). #[allow]ing it in thiserror means that anyone not on latest Rust/clippy and #[deny]ing all will run into build errors due to unknown_clippy_lints.

If there's a bug in clippy then it should be addressed by clippy, not by throwing breaking stopgap changes at it here.

Bonus points: clippy [just fixed it](https://github.com/rust-lang/rust-clippy/commit/3cc67785121c57d285987770bec9a49471639d18).

**Comment by dtolnay** [comment]
In general I am not interested in supporting old versions of Clippy. Clippy has enough churn that expecting clean builds of the same code across many versions of Clippy and many combinations of allow/deny attributes is not feasible.

**Comment by damianwadley** [comment]
You can certainly choose to do so, and I can't say I entirely disagree with the decision, but surely there's a middle ground here that allows us both to avoid the churn?

Most importantly for me, the clippy bug has been fixed, so would you consider reverting the 1.0.26 change and bringing us back to how things were before? I know my Jenkins builds would be very happy for that. nonstandard_macro_braces is a nursery lint and only available in nightly so it seems premature to even care about it in the first place.

And/or, how would you feel about adding `#[allow(clippy::unknown_clippy_lints)]`? If not now then perhaps next time clippy needs to be pacified. Ideally clippy would be able to recognize rules from the macro's source instead of the site where it's used, but short of that (which I don't believe is possible) I almost feel like unknown_clippy_lints should be copypasta for _all_ derive macros that need special clippy treatment...
