### ISSUE TITLE
Feature Request: Mapping function generation

### ISSUE THREAD

**Issue by Dessix** [dtolnay/thiserror#153]
I often run into scenarios where I want to manually collapse types down to a common error type without introducing another error "layer" between them, and `From` is too limited by the lack of negative bounds to do so generically across trait-constraints.

For Generic error types, it would be very convenient to have a feature which generates type-changing mapping / update methods. This is effectively `thiserror`-specific code generation for the [Type Changing Struct Update Syntax](https://github.com/rust-lang/rfcs/blob/master/text/2528-type-changing-struct-update-syntax.md), but this macro already has significant enough context on the types generated to make this easier than creating another proc-macro library.

Something like:
```rust
#[derive(thiserror::Error, Debug)]
#[error(mapper<A>("map_err"))]
enum MyError<A> {
  Generic(#[from] A),
  Fixed(String),
}
```

Could generate:
```rust
impl<A> MyError<A> {
  pub fn map_err<TNewA, F>(self, f: F) -> MyError<TNewA>
  where
    F: Fn(A) -> TNewA
  {
    match self {
      Self::Generic(a) => MyError<TNewA>::Generic(a),
      Self::Fixed(x) => MyError<TNewA>::Fixed(x),
    }
  }

  pub fn map_err_into<TNewA>(self) -> MyError<TNewA>
  where
    TNewA: From<A>
  {
    self.map_err(From::from)
  }
}
```

The place where this gets tedious to handle manually is around dealing with large numbers of cases, and the boilerplate around piping the unaltered cases through to the output. Additionally, creating this sort of mapper for multiple generic types means producing where clauses such that "Everything but this type parameter stays the same".

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate, but someone else could try making a crate for it.
