### ISSUE TITLE
Derive Serialize/Deserialize for external errors which are used with `#[from]`

### ISSUE THREAD

**Issue by oren0e** [dtolnay/thiserror#161]
If I have an enum error:
```rust
#[derive(Error, Debug, Serialize, Deserialize)]
pub(crate) enum RequestErrorInner {
    #[error(transparent)]
    HttpError(#[from] reqwest::Error),
    #[error("Error parsing request from json to string")]
    RequestParsingJsonError(#[from] serde_json::Error),
    #[error(transparent)]
    IOError(#[from] std::io::Error),
    #[error("Invalid unicode")]
    InvalidUTF8Error,
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}
```
I get compiler errors that basically require me to implement Serialize/Deserialize on the external errors that being used with `#[from]` ,e.g. `reqwest::Error`. How can I make it work? I don't know of any method to do this in `thiserror`.
I know there is a proposed [workaround](https://serde.rs/remote-derive.html) by serde, but it requires me to reconstruct all the error structure from the external crate, that is insanely inefficient. Any other workarounds/suggestions for this?

**Comment by dtolnay** [comment]
I don't think this issue has anything to do with thiserror because the errors are the same after removing all the thiserror attributes/derive from that code.

```rust
#[derive(Serialize, Deserialize)]
pub(crate) enum RequestErrorInner {
    HttpError(reqwest::Error),
    RequestParsingJsonError(serde_json::Error),
    IOError(std::io::Error),
    InvalidUTF8Error,
    Other(anyhow::Error),
}
```
