### ISSUE TITLE
Feature Request: Warnings for error message convention violation

### ISSUE THREAD

**Issue by Jonas-Heinrich** [dtolnay/thiserror#165]
Hi @dtolnay,

I love this project and am wondering whether it is possible to check for error message conventions while processing and raise a warning appropriately. For instance, it is standard to not leave a dot at the end of error messages or to capitalize anything.

The use case for this is in large projects with many different contributors and reviewers, where such mistakes can easily pass reviews and contribute to an inconsistent style.

For instance

```rust
/// Error categories for an example error
#[derive(Debug, Clone, thiserror::Error)]
enum ErrorExample {
    /// Example error variant
    #[error("Error description message.")]
    SomeError,
}
```

would result in a compiler warning something like this:

```
warning: error messages are lowercase by convention

    #[error("Error description message.")]
             ^^^^^

warning: error messages do not end in dots by convention

    #[error("Error description message.")]
                                      ^
```

While a complete configuration may be too much maintenance overhead, a feature toggle would probably be required. I am aware that [procedural macro diagnostics](https://github.com/rust-lang/rust/issues/54140) are currently unstable and probably a blocker at this point in time.

Thanks,
Jonas

**Comment by dtolnay** [comment]
Thanks for the suggestion! I would prefer not to build this into this crate though.

It would be reasonable for someone else to create a different derive macro that does this.
