### ISSUE TITLE
`use thiserror` prevents re-use in piggy-back proc-macros

### ISSUE THREAD

**Issue by drahnr** [dtolnay/thiserror#167]
First of all, ❤ thank you for all your work!

I recently started to create a proc-macro to piggy-back on `thiserror` to determine the fatality and convenient splitting of those error types ( https://github.com/drahnr/fatality ). Under the hood it generates `#[derive(fatality::thiserror::Error)]` annotated types, and as long as `thiserror` is part of the manifest in a compatible version with the re-export of `fatality`, everything works just fine.
As a matter of fact, I don't want the user to have to deal with this, `thiserror` is a impl detail that he should not be concerned with https://github.com/drahnr/fatality/issues/3 .

The root cause is the assumption of having a import of `thiserror` in a few places in the code that _generates_ statements like `use thiserror::private::AsDynError;` which are the root of the issue at hand.

Would you accept a patch to make the base of that use statement adjustable?

**Comment by dtolnay** [comment]
I would prefer not to build a workaround for this into this crate. If you are motivated to get this working, I would recommend thinking about an RFC that lets macro-generated code refer hygienically to a specific crate.

**Comment by dtolnay** [comment]
Something along the lines of https://github.com/rust-lang/rust/issues/54363#issuecomment-1237544924 would be my preferred approach, if you'd like to work on that.

**Comment by alexkirsz** [comment]
We're facing the same issue as OP. For now, we're doing `use ::macro_crate::__private::thiserror;`, which works well enough for our use case but pollutes the namespace.

For `serde`, we're using the [`crate` attribute](https://serde.rs/container-attrs.html#crate) to specify a custom path.

**Comment by suchyj-btlnet** [comment]
> I would prefer not to build a workaround for this into this crate. If you are motivated to get this working, I would recommend thinking about an RFC that lets macro-generated code refer hygienically to a specific crate.

Hi @dtolnay, is this preference still standing? We hit this problem in our proc-macros using thiserror and I wanted to make a PR here with a fix and reference repro repo for confirmation of the fix. I'm asking about that preference, because you were also behind the fix in the `serde` https://github.com/serde-rs/serde/pull/1499 where you approved `#[serde(crate="...")], so I'm puzzled why you approved merging this kind of fix in serde, but are prefering not to do it in thiserror.
