### ISSUE TITLE
What's the best practice to custom error message?

### ISSUE THREAD

**Issue by TennyZhuang** [dtolnay/thiserror#168]
Some error `Display` is non-trivial and cannot be represented by format string, e.g.:

```rust
#[derive(Error)]
pub enum Error {
    #[error("Feature {0} is not implemented, see https://repo_link/issues/{1}")]
    NotImplemented(String, Option<u32>),
// Other errors
}
```

The issue number is optional, then we should not display the link. The logic cannot be represented by format string.

I find two workarounds:

1. Create an alias type `type TrackingIssue(u32)` and customize Display for it.
2. Create a new `NotImplementedError` and make it transparent.

Both solutions are weird to use, is any better solution? Thanks!

**Comment by dtolnay** [comment]
Hi @TennyZhuang, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
