### ISSUE TITLE
#[error(transparent)] hides wrong error in chain()

### ISSUE THREAD

**Issue by muirdm** [dtolnay/thiserror#170]
I want the below to work:

```rust
#[derive(Debug, thiserror::Error)]
#[error("top: {0}")]
struct Top(#[source] Middle);

#[derive(Debug, thiserror::Error)]
#[error(transparent)]
struct Middle(Important);

#[derive(Debug, thiserror::Error)]
#[error("important")]
struct Important;

fn main() {
    let top: anyhow::Error = Top(Middle(Important {})).into();

    // I want this to pass.
    assert!(top.chain().any(|e| e.is::<Important>()));
}
```

But it doesn't because Middle's source() delegates to Important's source(), skipping over Important. Shouldn't MIddle be the error that doesn't show up in the chain?

I'm trying to use wrapper/tagging errors to mark things as e.g. a network error, but I'm having trouble because any transparent thiserror that contains a tag error gets skipped when an error introspecter looks at the chain().

**Comment by dtolnay** [comment]
That isn't what `transparent` means. `transparent` means this error's `Display` is the same as the field's `Display`, and this error's `source` is the same as the field's `source`.

**Comment by muirdm** [comment]
Thanks for responding.

Acknowledged it is working as documented. Intuitively it feels like I am marking "Middle" as transparent, so "Middle" should be the type that doesn't show up in the error chain.

Currently Display and source() are transparent, but the error type itself is not. Could `transparent` also delegate `is()` to the field?

**Comment by dtolnay** [comment]
If you want `Top`'s `source` method to return the `Middle`'s `source`, that is a property of `Top`'s `Error` impl. You can put a `transparent` attribute on `Top`.

**Comment by muirdm** [comment]
My example was over simplified. In reality "Middle" is an  enum with various error variants, one of which is a transparent "Other" anyhow::Error. "Top" doesn't want to transparent across everything in Middle.

Anyway, it makes sense it can't work the way I imagine since an error can't remove itself from the chain in general as you point out. It seems like I just need to not use transparent and do something different to avoid the redundant error output when displaying, as needed.
