### ISSUE TITLE
#[from] should support Option

### ISSUE THREAD

**Issue by phillord** [dtolnay/thiserror#171]
It would be nice to support `Option` as a `from` field.

I am thinking of the circumstance when I wish to abstract over an error which sometimes might come from an underlying error, but sometimes does not. For example, I am writing some code for parsing text. I might find that a word that is incorrectly spelled which would need to be signalled as an error. Or I might find that a token that is supposed to be a integer. In the former case, I will have an error message, in the later, I will have an `ParseIntError`.

```
pub enum Error {
     ParseError(String, #[from] Option(Box <dyn Error>)
}
```

The expansion of this should be natural enough since `source` already returns `Option`. Currently, this simply breaks the `Error` trait implementation in the expansion.

**Comment by dtolnay** [comment]
I would prefer not to build this into this library. The `from` functionality is not intended to be a general purpose `From` derive, only for the `From` conversions done inside `?`. From your description it does not sound like that applies to your case.

**Comment by phillord** [comment]
Fair enough! Thank you for considering the issue.
