### ISSUE TITLE
Making error string optional

### ISSUE THREAD

**Issue by Pzixel** [dtolnay/thiserror#172]
Consider following error:

```rust
#[derive(Debug, thiserror::Error)]
pub enum ExactLengthError {
    #[error("Too small")]
    TooSmall,
    #[error("Too big")]
    TooBig,
}
```

The problem here is that `Too small` isn't a big improvement over `TooSmall`. Sometimes errors are self-explanatory and do not need additional description.

i wish it was possible to write:

```rust
#[derive(Debug, thiserror::Error)]
pub enum ExactLengthError {
    TooSmall,
    TooBig,
    #[error("Proper description (expected {expected:?}, found {found:?})")]
    ThisIsTheVariantThatNeedsProperDescription {
        expected: String,
        found: String,
    },
}
```

And use debug representation as string for variants that do not provide any custom string

**Comment by dtolnay** [comment]
I would prefer to keep it required.
