### ISSUE TITLE
Deriving structs with `backtrace` fails since `fn backtrace` has been removed from `Error`

### ISSUE THREAD

**Issue by Systemcluster** [dtolnay/thiserror#177]
As of https://github.com/rust-lang/rust/pull/99431 `fn backtrace` is not part of `Error` anymore. This causes derives with `backtrace` to fail; And the following example results in a compilation error.

```
method `backtrace` is not a member of trait `std::error::Error`
not a member of trait `std::error::Error`
```

```rust
#[derive(Error, Debug)]
#[error("Platform Error {code}")]
pub struct PlatformError {
    backtrace: Backtrace,
    code:      i32,
}
```

**Comment by MomoLangenstein** [comment]
I've been experiencing the same issue

**Comment by dtolnay** [comment]
This is blocked on https://github.com/rust-lang/rust/issues/100399.

**Comment by dtolnay** [comment]
Perhaps not &mdash; it looks like `anyhow` uses BacktraceStatus but `thiserror` does not.

**Comment by Xuanwo** [comment]
Do we need to remove the backtrace method?

https://github.com/dtolnay/thiserror/blob/1442e27eafc8d8ee26eeea433c3847a9c6d7cc0c/impl/src/expand.rs#L62-L104
