### ISSUE TITLE
[Question] Can the error message from the `#[error(...)]` attribute be returned to the end-user (API)?

### ISSUE THREAD

**Issue by enheit** [dtolnay/thiserror#178]
I'm new to Rust lang and looking for the best practices of how to handle errors. 

Before starting to use this library I managed errors like this

```rs
enum UserErrors {
    UserNotFound { message: Strimg, user_id: String } 
}

fn get_user (user_id: String) -> Result<User, UserErrors> {
    if /* user not found */ {
        return Err(UserErrors::UserNotFound { message: "User was not found", user_id: user_id })
    }
}

fn main() {
    match get_user("id_1") {
       Ok(user) => /* handle user */,
       Err(errors) => match errors {
           UserErrors::UserNotFound { message, user_id } => println!(message); // I use message from UserNotFound to return in API
       }
   }
}
```

After refactoring to the `thiserror` approach my code now looks like this

```rs
#[derive(Debug, thiserror::Error)]
enum UserErrors {
    #[error("User was not found")]
    UserNotFound { user_id: String } 
}

fn get_user (user_id: String) -> Result<User, UserErrors> {
    if /* user not found */ {
        return Err(UserErrors::UserNotFound { user_id: user_id })
    }
}

fn main() {
    match get_user("id_1") {
       Ok(user) => /* handle user */,
       Err(errors) => match errors {
           UserErrors::UserNotFound { user_id } => println!(??? message ???); // How to get access to the error message? 
       }
   }
}
```

I found this sentence inside the documentation

> Thiserror deliberately does not appear in your public API.

I treat it like this: "All error messages that are written inside `#[error("My lovely error message")` attribute only for development purposes. If you want this error message to be returned inside API create a new one.

Am I understanding this correctly? 

I'm confused because `Display` trait is used for showing for users (end users?). 

What is the best practice of this lib? Should I reuse (somehow) the error message that was declared inside `#[error(...)]` attribute, or create a new error message for API?

**Comment by stefunctional** [comment]
You can do this:
```rust
#[derive(Debug, thiserror::Error)]
enum UserErrors {
    #[error("User {user_id} was not found")]
    UserNotFound { user_id: String } 
}

struct User;

fn get_user(user_id: &str) -> Result<User, UserErrors> {
    Err(UserErrors::UserNotFound { user_id: user_id.into() })
}

fn main() {
    match get_user("id_1") {
       Ok(_) => /* handle user */{}
       Err(errors) => println!("{errors}"),
   }
}
```
Output:
```text
User id_1 was not found
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b269e41c3af50c0f9a4fec8a482b8cca)
