### ISSUE TITLE
Macro for `cause` and `description`.

### ISSUE THREAD

**Issue by BratSinot** [dtolnay/thiserror#180]
Greetings!

Am I missing something, but there exist `#[source]` for `source(&self)` method, `#[backtrace]` for `backtrace(&self)`, but no macro for `description` and `cause`?

**Comment by dtolnay** [comment]
Correct, there is no reason to ever use those methods.

**Comment by BratSinot** [comment]
> there is no reason to ever use those methods

Wait, why??
