### ISSUE TITLE
Deriving `fmt::Display` from doc comments

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [dtolnay/thiserror#181]
It is common to see an error type like:
```rust
#[derive(Debug, thiserror::Error)]
pub enum MyError {
    /// Process A failed.    
    #[error("Process A failed: {0}")]
    SubErrorA(A),
    /// Process B failed.
    #[error("Process B failed: {0}")]
    SubErrorB(B)
}
```
Which leads me to think it would be possible to avoid requiring `#[error("Process A failed: {0}")]` and `#[error("Process B failed: {0}")]` by simply using the `#[doc="Process A failed."]` and `#[doc="Process B failed."]`. It could use `#[error]` if present, otherwise fallback to `#[doc]`.

E.g. :
```rust
#[derive(Debug, thiserror::Error)]
pub enum MyError {
    /// Process A failed.    
    SubErrorA(A),
    /// Process B failed.
    SubErrorB(B)
}
```

It could be behind a feature e.g. `from_doc_comments` so it doesn't surprise people.

Does this seem like something worth creating a PR for?

**Comment by dtolnay** [comment]
I am not interested in building this into thiserror, but you can use thiserror's Error derive and a different derive for the Display impl.
