### ISSUE TITLE
Stable build fails

### ISSUE THREAD

**Issue by GCNull** [dtolnay/thiserror#208]
I'm unable to build on stable due to the following error:

```rust
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.37/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^
```
rustc version: ``rustc 1.65.0 (897e37553 2022-11-02)``

**Comment by Grollicus** [comment]
`cargo clean` solved this for me, this also seems to be https://github.com/dtolnay/thiserror/issues/192

**Comment by GCNull** [comment]
Thanks a lot! I thought this was a new issue with rustc 1.65 so I didn't scroll down far enough. Closing as ``cargo clean`` also fixes it for me.
