### ISSUE TITLE
I'm trying to wrap my head around the process of creating a derive macro. How much inspiration can I take from your code before I need a license?

### ISSUE THREAD

**Issue by NullSurplus** [dtolnay/thiserror#216]
I'm making a derive macro and I'm kinda in a hurry. The way `thiserror` is composed seems to be fairly straightforward, and I don't want to reinvent the wheel, but I also don't want to have to worry about licensing issues.

If I'm making a completely new derive macro for a different purpose, can I copy the basic scaffolding of `thiserror` (identifiers, architecture) without having to include the licenses? Or do I need to include the licenses even if I'm making a different derive macro?

Sorry for submitting this to the issues if this is the wrong place (or wrong question).

**Comment by dtolnay** [comment]
I do not feel comfortable dispensing legal advice on this topic.
