### ISSUE TITLE
Catching Serde deserializer error

### ISSUE THREAD

**Issue by 0cv** [dtolnay/thiserror#218]
I've been using `thiserror` across various libraries successfully, but got stuck while implementing a custom deserializer for Serde which has the specificity of requiring lifetimes but especially generics in the trait.

This looks like this:
```
impl<'de> Deserialize<'de> for MyType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
.....
    }
}
```

And I tried to turn it like this:

```
#[derive(Debug, Error)]
pub enum DeserializerCustomError<
    'de,
    D: Deserializer<'de>
> {
    #[error("error")]
    DeserializeError(#[from] D::Error),
}

impl<'de> Deserialize<'de> for MyType {
    fn deserialize<D>(deserializer: D) -> Result<Self, DeserializerCustomError<'de, D>>
    where
        D: Deserializer<'de>,
    {
.....
    }
}
```

Unfortunately I get `conflicting implementation in crate `core`: impl<T> From<T> for T;`. I've seen similar issues reported in https://github.com/dtolnay/thiserror/issues/85 or https://github.com/dtolnay/thiserror/issues/156 but I was hoping that there might be a workaround for this specific use case?

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. Serde and thiserror are each one of the most widely used Rust libraries, so plenty of people will be able to help you out.
