### ISSUE TITLE
Nested Errors Question

### ISSUE THREAD

**Issue by tr3ysmith** [dtolnay/thiserror#219]
Hey everyone! So far I absolutely love this crate! It's saved me so much time in my projects! One thing I'm running into though is nested Errors, and I have a question on best practices or maybe if there's a better way...

Here's an example:
```rust
#[derive(Debug, Error)]
pub enum Error {
    #[error("other error 2 - {0}")]
    Error2(#[from] Error2)
}

#[derive(Debug, Error)]
pub enum Error2 {
    #[error("another error 3 - {0}")]
    Error3(#[from] Error3)
}

#[derive(Debug, Error)]
pub enum Error3 {
    #[error("This is error 3")]
    SomethingHappened
}


fn overall_result() -> Result<(), Error> {

    result_with_error2()?; // Works fine

    result_with_error3()?; // Does not work as is
    result_with_error3().map_err(|e| Error2::Error3(e))?; // But doing this fixes it

    Ok(())

}

fn result_with_error2() -> Result<(), Error2> {
    //...
}

fn result_with_error3() -> Result<(), Error3> {
    //...
}

```

So my question is, is mapping the error up a level the right way? I know this example is somewhat arbitrary, but I have child modules within other modules and I'm trying to keep the local module's errors collected in one place and then allow the parent module to implement the `#[from]` for it. At my top level, I have an overall Error enum that aggregates all modules.

Thanks in advance!

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
