### ISSUE TITLE
Specifying #[from] without exposing underlying error

### ISSUE THREAD

**Issue by Artem-Romanenia** [dtolnay/thiserror#224]
Hi,

I`m trying to apply thiserror to  similar enum:

```rust
#[derive(Error, Debug)]
pub enum ParserError {
    #[error("IO Error")]
    IoError(#[from] std::io::Error),
    #[error("Json Error")]
    JsonError(#[from] serde_json::Error)
}
```

With this code it works exactly how I want it to.

But if I don't  want to expose third party error through `ParserError`, I end up with this

```rust
#[derive(Error, Debug)]
pub enum ParserError {
    #[error("IO Error")]
    IoError(#[from] std::io::Error),
    #[error("Json Error")]
    JsonError(SomeErrorRepresentation)
}
```

And I'm loosing convertability between `ParserError` and `serde_json::Error`

Is there any way to keep `ParserError` convertible to `serde_json::Error` except for manually implementing the `from` trait? Perhaps something similar to this:

```rust
#[derive(Error, Debug)]
pub enum ParserError {
    #[error("IO Error")]
    IoError(#[from] std::io::Error),
    #[error("Json Error")]
    #[from(serde_json::Error)] //obviously code for converting from `serde_json::Error` to `ParserError` has to be provided somehow as well
    JsonError(SomeErrorRepresentation)
}
```
I can see that `#[from]()` is allowed on variant level, but perhaps for different purpose.

P.S. I've just recently started learning Rust, so please forgive me if I`m missing something obvious here. Any help or comments are greatly appreciated.

**Comment by dtolnay** [comment]
I prefer not to build anything for this into this crate. Someone can make a general purpose `From` derive in a different crate.
