### ISSUE TITLE
Strange error with `#[from]`.

### ISSUE THREAD

**Issue by BratSinot** [dtolnay/thiserror#229]
Greetings!

I got strage error with auto-from generate. In this code:
```rust
#[derive(Debug, thiserror::Error)]
enum MyError {
    #[error("{0}")]
    // NOT OK
    Conversion(#[from] <u32 as TryFrom<i32>>::Error),
    // OK
    //Conversion(<u32 as TryFrom<i32>>::Error),
}

fn main() {
    let snum = 123i32;

    // NOT OK
    let _num = u32::try_from(snum).map_err(MyError::from);
    // OK
    //let _num = u32::try_from(snum).map_err(MyError::Conversion);
}
```
I got error:
```log
error[E0119]: conflicting implementations of trait `std::convert::From<MyError>` for type `MyError`
 --> src/main.rs:1:17
  |
1 | #[derive(Debug, thiserror::Error)]
  |                 ^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> std::convert::From<T> for T;
  = note: upstream crates may add a new impl of trait `std::convert::From<i32>` for type `u32` in future versions
  = note: this error originates in the derive macro `thiserror::Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```

P.S. `thiserror` version is `1.0.40`

**Comment by dtolnay** [comment]
This is working correctly as far as I can tell.

If you're able to share what code you were expecting it to generate, I can take another look.

**Comment by BratSinot** [comment]
> This is working correctly as far as I can tell.

How????

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2897112cffa1974d1b776c0795046d18

<img width="909" alt="image" src="https://user-images.githubusercontent.com/3810015/231801964-20179bbb-e080-4d72-9e8d-aaf4a816f727.png">
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/3810015/231802157-4e646dcd-8949-4219-8dbd-6023ab86cb8d.png">
