### ISSUE TITLE
`anyhow::Error` as `#[source]` does not work generically

### ISSUE THREAD

**Issue by chbaker0** [dtolnay/thiserror#231]
With

```rust
#[derive(Debug, Error)]
#[error("uh oh")]
struct FooError<Inner> {
    #[source]
    source: Inner,
}
```

`FooError<anyhow::Error>` does not implement `Error` due to the `Inner: Error` bounds on generic arguments. Meanwhile, as called out in the docs, this _does_ work:

```rust
#[derive(Debug, Error)]
#[error("all good")]
struct FooError {
    #[source]
    source: anyhow::Error,
}
```

since `source` will implicitly deref to `dyn Error`.

Can the docs mention the difference?

Alternatively, is there any way for this to work? It would be nice to generically include a source error that could either be an `Error` itself or dereference to one. Maybe it's relevant that `anyhow::Error` has an `AsRef<dyn Error + Sync + Send + 'static>` impl (though of course you'd know that)

**Comment by chbaker0** [comment]
Actually found a workaround that is perfectly reasonable for me.

```rust
#[derive(Debug, Error)]
#[error("{source}")]
struct AnyhowWrapper {
    #[from]
    source: anyhow::Error,
}
```

and simply using that in `FooError<AnyhowWrapper>`.

**Comment by dtolnay** [comment]
I think the workaround you found is the way to go.
