### ISSUE TITLE
A modest proposal for no_std support

### ISSUE THREAD

**Issue by udoprog** [dtolnay/thiserror#232]
I'm [using thiserror in rune](https://github.com/rune-rs/rune/blob/main/crates/rune/src/compile/error.rs#L181), and I've recently added no_std support to it. A painpoint to implement this is thiserror, but I've temporarily managed to get it to work.

The way I went about incorporating it was to [fake the private API of thiserror](https://github.com/rune-rs/rune/blob/main/crates/rune/src/no_std/thiserror.rs) (also known as the "fake std" approach [being discussed here](https://github.com/dtolnay/thiserror/pull/64#issuecomment-612570677)). While this works and gets things compiling, it's unfortunately fragile since the expected structure of the internal API is not guaranteed to stay the same.

If thiserror could provide the following guarantees the fake std approach would be viable for no_std (even if it's a bit tricky to use):
* A stable API of `AsDynError` and a stable path used by `thiserror-impl`.
* A stable API of `DisplayAsDisplay ` and a stable path used by `thiserror-impl`.

Alternatively, some way to customize the behavior of the derive, like `error(as_display_with = <path>)` and `error(as_error_with = <path>)` on the container.

Since you're already using stable parts of `std::error::Error`, that would not have to change.

If anyone is curious, the reason why you'd need a local `AsDynError` is because you currently have to shim in a [no_std version of the `Error` trait](https://github.com/rune-rs/rune/blob/main/crates/rune/src/no_std/error.rs). Using the one provided by `thiserror` would reference the `std` trait.

Without something like this (or an alternative approach which can survive incompatible upgrades of `thiserror-impl`), I'll have to remove the use of thiserror before the next release. So I hope something can be worked out but I also understand if this is out of scope.

Thank you!

**Comment by ariel-miculas** [comment]
I'm also interested in `no_std` support, particularly for use in the linux kernel.

**Comment by dtolnay** [comment]
I would prefer not to provide either of the guarantees you suggest.
