### ISSUE TITLE
Add support for the `alterante` flag.

### ISSUE THREAD

**Issue by xfbs** [dtolnay/thiserror#234]
Hey David,

I might be on the wrong track here (would appreciate some input). I would like for `thiserror` to generate a `Display` implementation that also has special handling for the `alternate` flag, such that by default we only get the immediate message of the current error, but optionally we can get the chain of causes as well. Basically:

```rust
format!("{error}") -> "cannot make request"
format!("{error:#}") -> "cannot make request: this thing failed: other thing failed first"
```

I've opened up PR #233 that works for a simple local prototype but does not pass unit tests.

What is your thoughts on this? If you think this makes sense, I would quite like to build it. Is there some downsides with doing this?

Cheers!

**Comment by dtolnay** [comment]
I would prefer not to support this. But `derive(Error)` is compatible with other libraries that provide `derive(Display)` so you should feel free to use any of those.
