### ISSUE TITLE
Interop with other error libs

### ISSUE THREAD

**Issue by hcldan** [dtolnay/thiserror#235]
Trying to figure out what the best option is here, or who to contact.

I'm using `rasn` and would like to capture a `rasn::ber::de::Error`
```rust
#[derive(Error, Debug)]
pub enum MyError {
	#[error("ASN.1 Error")]
	ASN1Error(#[from] rasn::ber::de::Error),
}
```

But I get: 
```
the method `as_dyn_error` exists for reference `&rasn::ber::de::Error`, but its trait bounds were not satisfied
the following trait bounds were not satisfied:
`rasn::ber::de::Error: StdError`
which is required by `rasn::ber::de::Error: AsDynError<'_>`
`&rasn::ber::de::Error: StdError`
which is required by `&rasn::ber::de::Error: AsDynError<'_>`
```

Is this the responsibility of the `rasn` crate?  
The crate is using `snafu` for errors...  should this be done by the `snafu` crate?
Is this something that could be done here as a catchall for snafu errors?

**Comment by dtolnay** [comment]
That means there is no `impl std::error::Error for rasn::ber::de::Error`.

That impl can only be provided by the rasn crate.

**Comment by hcldan** [comment]
@dtolnay is this typical of error handling libraries to not automagically do that?
