### ISSUE TITLE
Suggestion: Automatically generate documentation comments based on display string

### ISSUE THREAD

**Issue by naturecodevoid** [dtolnay/thiserror#245]
Library authors may want to use the same text for documentation comments as the error message given to thiserror for generating a `Display` implementation. While they could copy and paste it, I think it might be nice to automatically copy the text into a documentation comment.

Using the example from the README as an example:
```rs
#[derive(Error, Debug)]
#[thiserror(copy_all_error_messages_to_docs)]
pub enum DataStoreError {
    #[error("data store disconnected")]
    /// data store disconnected
    Disconnect(#[from] io::Error),
    #[error("the data for key `{0}` is not available")]
    /// the data for key `{0}` is not available
    Redaction(String),
    #[error("invalid header (expected {expected:?}, found {found:?})")]
    /// invalid header (expected {expected:?}, found {found:?})
    InvalidHeader {
        expected: String,
        found: String,
    },
    #[error("unknown data store error")]
    /// unknown data store error
    Unknown,
}
```

To enable this functionality, a `copy_all_error_messages_to_docs` option could be used in the `thiserror` / `error` outer attribute. It could also be applied individually to enum variants with a `copy_error_message_to_docs` option.

If there is already documentation on the item, it would not be overwritten.

One possible issue with this is when the error message uses formatting parameters. Most Rust users are familiar with the syntax of format! macros, so they should be able to read the messages pretty easily. However, issues may arise in situations such as `#[error("{}", i32::MAX)]`, `#[error("{:?}", first_char(.0))]` and `#[error("{}", .limits.lo)]`. Those situations could just be a caveat of using the option if there's not a good way to handle it.

If this seems like a good feature, you may want to think of a more clear name for the attribute option.

**Comment by dtolnay** [comment]
Derive macros are not able to modify documentation of the data structure that is the target of the derive.
