### ISSUE TITLE
Implement `?` syntax for any Result<_, E> (where E is thiserror) that calls map_err(Error::from) firsts

### ISSUE THREAD

**Issue by ddevcrimson** [dtolnay/thiserror#249]
I have such a problem with errors from this crate that before calling `?`, I need to call Result::map_error(Error::from) to implicitly convert to thiserror type from the type annotated with #[from] in the variant. It would be cool if it was functionality built into the crate.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate, but I would be interested to see someone attempt this in a fork.
