### ISSUE TITLE
Non-consuming container attribute reports an unused variable

### ISSUE THREAD

**Issue by miraclx** [dtolnay/thiserror#259]
`rust-analyzer` complains about this syntax, even though it's valid according to this crate. `rustc` doesn't report any issues.

```rust
#[derive(Debug, Error)]
#[error("MyError")]
pub enum MyError {
    Variant { field: () },
}
```

Seems to expand to this

```rust
#[allow(unused_qualifications)]
impl std::error::Error for MyError {}

#[allow(unused_qualifications)]
impl ::core::fmt::Display for MyError {
    fn fmt(&self, __formatter: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        #[allow(unused_variables, deprecated, clippy::used_underscore_binding)]
        match self {
            MyError::Variant { field } => ::core::write!(__formatter, "MyError"),
        }
    }
}
```

In the match statement, `field` is indeed unused.

**Comment by miraclx** [comment]
I believe the same logic that includes the `field = field` associations when `{field}`s are present in the format string can be used here. We'll just make sure to accommodate the lack of them with the spread operator `..`.

**Comment by dtolnay** [comment]
If rustc does not report any warning, isn't this a rust-analyzer bug?

**Comment by miraclx** [comment]
Yeah, I agree with you there.. Curious why it doesn't work, but in this case, I thought to file here as well since it is possible to avoid them. Feel free to close if you don't think it worthwhile to resolve.

I'll also file an issue with RA.
