### ISSUE TITLE
backtrace::Backtrace instead of std::backtrace?

### ISSUE THREAD

**Issue by jondot** [dtolnay/thiserror#262]
Hi,
Using backtrace captures, I'm trying to figure out how to use libraries like color-backtrace (which needs backtrace::Backtrace from `backtrace-rs`).
Looks like std::backtrace functionality is still guarded with a lot of unstable feature flagging, and so is very limited.
Anyone bumped into this?

**Comment by dtolnay** [comment]
I don't plan to support backtrace-rs's `Backtrace` natively in this crate, only `std::backtrace::Backtrace`. But I think there are other error handling libraries that could work better for you.
