### ISSUE TITLE
v1.0.52 update causing constant recompilation

### ISSUE THREAD

**Issue by Turbo87** [dtolnay/thiserror#270]
After merging https://github.com/rust-lang/crates.io/pull/7808 I noticed that some dependencies started to recompile for every build. I just ran a `git bisect` session and could reproduce the issue:

<img width="480" alt="Bildschirmfoto 2023-12-28 um 11 59 54" src="https://github.com/dtolnay/thiserror/assets/141300/e7ec2bcd-76d4-4086-bc2f-75588aafa385">

I assume this is most likely related to:
- https://github.com/dtolnay/thiserror/pull/269

**Comment by Turbo87** [comment]
It looks like anyhow v1.0.77 is causing similar issues

**Comment by dtolnay** [comment]
How can I reproduce this? I ran `cargo check --workspace` in rust-lang/crates.io twice and nothing got recompiled.

**Comment by Turbo87** [comment]
hmm, I noticed it while running tests from within IntelliJ. I'll try and reproduce it on the command line once I'm back on the computer tomorrow.

**Comment by Turbo87** [comment]
looks like IntelliJ is more or less at fault here... when running the test suite inside of IntelliJ it is first compiling the test code via:

```
cargo test --color=always --no-run --package crates_io --lib rate_limiter::tests
```

and then running the tests with:

```
cargo test --color=always --package crates_io --lib rate_limiter::tests --no-fail-fast -- --format=json -Z unstable-options --show-output
```

if I try to run the latter on the CLI outside of IntelliJ I get:

```
error: the option `Z` is only accepted on the nightly compiler
error: test failed, to rerun pass `-p crates_io --lib`
error: 1 target failed:
    `-p crates_io --lib`
```

so I guess IntelliJ might be using `RUSTC_BOOTSTRAP` to enable usage of `-Z unstable-options` on the stable compiler 🙈

**Comment by Turbo87** [comment]
https://youtrack.jetbrains.com/issue/RUST-13133/RUSTCBOOTSTRAP1-is-passed-to-test-configuration seems to confirm my suspicion :-/

**Comment by dtolnay** [comment]
Good catch. I commented on the RustRover issue tracker with my suggested fix.
