### ISSUE TITLE
Doesn't work with `core::error::Error`

### ISSUE THREAD

**Issue by Scripter17** [dtolnay/thiserror#271]
For some reason [`publicsuffix::Error`](https://docs.rs/publicsuffix/latest/publicsuffix/enum.Error.html#impl-Error-for-Error) implements `core::error::Error` but not `std::error::Error`.

I think it should be possible to wrap around that type using just `#[from]`, but currently it's a compilation error.

```
 1  error[E0599]: the method `as_dyn_error` exists for reference `&Error`, but its trait bounds were not satisfied
   --> src/suffix.rs:23:18
    |
 23 |     ParseError(#[from] Error)
    |                  ^^^^ method cannot be called on `&Error` due to unsatisfied trait bounds
    |
   ::: /home/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/publicsuffix-2.2.3/src/error.rs:7:1
    |
 7  | pub enum Error {
    | --------------
    | |
    | doesn't satisfy `_: AsDynError<'_>`
    | doesn't satisfy `publicsuffix::Error: std::error::Error`
    |
    = note: the following trait bounds were not satisfied:
            `publicsuffix::Error: std::error::Error`
            which is required by `publicsuffix::Error: thiserror::__private::AsDynError<'_>`
            `&publicsuffix::Error: std::error::Error`
            which is required by `&publicsuffix::Error: thiserror::__private::AsDynError<'_>`
```

A related issue is this is just not a good error message, but that's probably a bit harder to fix.

**Comment by dtolnay** [comment]
`core::error::Error` and `std::error::Error` are the same trait. It is not possible to implement one but not the other.

According to [this code](https://github.com/rushmorem/publicsuffix/blob/v2.2.3/src/error.rs#L30-L31), `publicsuffix::Error` implements `Error` only if feature="std" is enabled. Probably you have not enabled that feature.
