### ISSUE TITLE
`#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by erikschul** [dtolnay/thiserror#281]
I get this error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /workspace/.cargo/registry/src/index.crates.io-3f57d32bcxa43101f/thiserror-1.0.56/src/lib.rs:238:50
    |
238 | #![cfg_attr(error_generic_member_access, feature(error_generic_member_access))]
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

for this code
`lib.rs`
```
#![cfg_attr(error_generic_member_access, feature(error_generic_member_access))]
```

Is this intentional?

**Comment by dtolnay** [comment]
Would you be able to provide what commands I need to run in order to reproduce this?

**Comment by erikschul** [comment]
Hmm, maybe this happened when I was experimenting with installing build time optimizations (cargo machete etc.). I faintly recall one of them required switching to nightly, installed a dependency, and maybe I then switched back, the cargo cache was still using the `nightly` version of the crate. I think it resolved after using `cargo clean`.

**Comment by dtolnay** [comment]
If you hit this again and are able to come up with a sequence of commands that deterministically reproduces the behavior, I am very interested to hear. It's possible it reveals a bug in cargo-machete, or cargo, or thiserror, or something else.

**Comment by Atlas16A** [comment]
After doing `rustup update stable` i encountered this error in my bevy 0.12 project. A `cargo clean` successfully fixed it, however the error is fake. it does not cause a failure to compile and only blocked rust analyzer from properly checking my code.
I believe its an error in either rustup or cargo.

**Comment by GoldsteinE** [comment]
I think that’s fixed now. Reproduction:
```console
$ # Some outputs are omitted for brevity
$ # Reproducible environment:
$ podman run --rm -it rust:1.78.0 bash
$ cd
$ cargo new ttt
$ cd ttt
$ # Doesn't seem to work on the latest version.
$ # I didn't bisect it though, so 1.0.47 may not be the latest one broken.
$ cargo add thiserror@=1.0.47
$ RUSTC_BOOTSTRAP=1 cargo build -q
$ cargo build -q
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.47/src/lib.rs:239:50
    |
239 | #![cfg_attr(error_generic_member_access, feature(error_generic_member_access))]
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` (lib) due to 1 previous error
```
