### ISSUE TITLE
feature request: generate source trait and implementation to ease adding context

### ISSUE THREAD

**Issue by glehmann** [dtolnay/thiserror#283]
I've been using this kind of trait in my code to ease adding context in an error. The usual one in adding some path context to an `io::Error`:

~~~rust
#[derive(Debug, Error)]
enum Error {
    #[error("{path}: {source}")]
    PathIo { source: io::Error, path: PathBuf },
    // other error variants…
}

trait ErrorPathIoCtx<T> {
    fn path_ctx<P: Into<PathBuf>>(self, path: P) -> result::Result<T, Error>;
}

impl<T> ErrorPathIoCtx<T> for result::Result<T, io::Error> {
    fn path_ctx<P: Into<PathBuf>>(self, path: P) -> result::Result<T, Error> {
        self.map_err(|source| Error::PathIo {
            source,
            path: path.into(),
        })
    }
}
~~~

which ease quite a lot adding context to an `io::Error` while converting it to my custom error:

~~~rust
    fs::create_dir_all(&cache_dir).path_ctx(&cache_dir)?;
~~~

I haven't found the feature to generate that code in thiserror so far — sorry if it's there or already has been discussed and I missed it!

I see in #42 that thiserror couldn't add a generic context in order to not taint the generated error with a thiserror trait. The kind of construct proposed here doesn't depend on any external trait, so I think that may be an acceptable solution :-)

That could be used with something like:

~~~rust
#[derive(Debug, Error)]
enum Error {
    #[error("{path}: {source}")]
    PathIo {
        source: io::Error,
        #[ctx]
        path: PathBuf,
    },
    // other error variants…
}
~~~

* the source type can be used to generate the `for result::Result<T, io::Error>` bit
* the enum name and the variant name to generate the `impl<T> ErrorPathIoCtx<T>` part
* the field marked with `#[ctx]` and the enum name to generate the `fn path_ctx<P: Into<PathBuf>>(self, path: P) -> result::Result<T, Error>`

I didn't had a need for that myself, but the generated trait could also generate the lazy version of `path_ctx`: `with_path_ctx` or `path_ctx_with` or …

**Comment by dtolnay** [comment]
Thanks for the suggestion. I would prefer not to build this into this library.

**Comment by glehmann** [comment]
Ok, no problem :-)

Out of curiosity, could you share why you prefer to not have it in thiserror?
