### ISSUE TITLE
derive `Error` without `Display` impl

### ISSUE THREAD

**Issue by evbo** [dtolnay/thiserror#290]
Hi,

In the readme you show `from`  being used without `Display` implemented:

```rust
#[derive(Error, Debug)]
pub enum MyError {
    Io {
        #[from]
        source: io::Error,
        backtrace: Backtrace,
    },
}
```

This is useful in my particular case because if my enum implements Display that will conflict with an `Into` from a third-party library that is implementing it for `T: Display`. I am happy to just use `Debug`.

However, if I try to just derive `Error` without Display I get:
```rust
   |
32 | pub trait Error: Debug + Display {
   |                          ^^^^^^^ required by this bound in `Error`
```

Is it possible to just impl `From` and not `Display` using `thiserror`?

**Comment by evbo** [comment]
in case it's helpful, here is the third party `Into` I need to use, and hence why my enum can't impl `Display`:
https://github.com/awslabs/aws-lambda-rust-runtime/blob/e0e95e61cba0a8a695d4766d9215cbe839caf3a7/lambda-runtime/src/types.rs#L67-L77

**Comment by dtolnay** [comment]
Thiserror doesn't have anything to do with this requirement. Anything implementing std::error::Error is also required to implement both Debug and Display. The line in the diagnostic you pasted is from https://doc.rust-lang.org/1.76.0/std/error/trait.Error.html.

```rust
pub trait Error: Debug + Display {
```
