### ISSUE TITLE
Empty structures are not supported

### ISSUE THREAD

**Issue by mathstuf** [dtolnay/thiserror#3]
Should this be valid?

```rust
#[derive(Debug, Error)]
struct EmptyStruct;
```

Or should this have a custom `Display` impl (if so, docs on it would be nice).

Empty `enum` seems fine since that is just `Void`. Though I guess `None` is fine for the implementation of the methods there…

**Comment by dtolnay** [comment]
It works for me! You either need to provide the Display impl:

```rust
#[derive(Debug, Error)]
struct EmptyStruct;

impl Display for EmptyStruct {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        /* ... */
    }
}
```

or give an attribute with the Display message if you want derive(Error) to write the impl:

```rust
#[derive(Debug, Error)]
#[error("...")]
struct EmptyStruct;
```

**Comment by mathstuf** [comment]
Ah, didn't realize the attribute worked on non-fields or variants. Thanks!
