### ISSUE TITLE
Using `{:p}` in `#[error]` uses the address of the field, not the value of the field

### ISSUE THREAD

**Issue by frozenlib** [dtolnay/thiserror#300]
In the following code, `Display` implementation outputs the address of the field, not the value of the field.

```rust
#[derive(thiserror::Error, Debug)]
#[error("{p:p}")]
struct E {
    p: *const u32,
}
let p: *const u32 = &0;

println!("value {:p}", p);
println!("addr  {:p}", &p);
println!("error {}", E { p });
```
output:
```
value 0x7ff688a9c568
addr  0xfb9836f6a8
error 0xfb9836f7a8
```

It seems to me that the expected behavior is to output the value of the field.

**Comment by dtolnay** [comment]
I don't know any way it could be implemented that way in thiserror. But you can write `#[error("{:p}", *p)]` to render the pointer's value as opposed to the address of the pointer.
