### ISSUE TITLE
clippy result_large_err

### ISSUE THREAD

**Issue by extrawurst** [dtolnay/thiserror#302]
When composing my error type of sub error types it quickly happens that it will trigger this clippy lint: `result_large_err`.

This often makes me either ignore/allow that lint or type that error as String and write a manual `From` impl to convert. I was wondering if there is a way to have this crate create this error conversion for me, such as that I create a specific enum value for this error in my Error type and give it a macro marking it as a simple `to_string()` conversion from a given `Error SubType`?

**Comment by dtolnay** [comment]
You can write your own `From` impl to apply whatever conversion you want.

```rust
impl From<OtherError> for MyError {
    fn from(e: OtherError) -> Self {
        MyError::Other(e.to_string())
        //or MyError::Other(Box::new(e))
    }
}
```

**Comment by JMLX42** [comment]
> You can write your own From impl to apply whatever conversion you want.

I think writing one's own `From` impl kinda makes `#[from]` useless.

IMHO the whole point of `thiserror` is to make a hassle free wrapper for multiple error types. And the `result_large_err` warning makes it impossible without `Box`.
