### ISSUE TITLE
Warning regarding private macro use on Rust 1.79

### ISSUE THREAD

**Issue by gschulze** [dtolnay/thiserror#306]
I am getting the following warning on recent Rust versions. Although not an error, it would be nice to export the macro properly in a future release.

warning: macro `Error` is private
  --> path/to/file.rs:40:10
   |
   | #[derive(Error, Debug)]
   |          ^^^^^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #120192 <https://github.com/rust-lang/rust/issues/120192>
   = note: `#[warn(private_macro_use)]` on by default

**Comment by dtolnay** [comment]
The macro is exported properly in thiserror. The warning you got is probably related to a `use` in some other crate in your dependency graph, but you haven't shared a way to reproduce it.
