### ISSUE TITLE
how to print source in display format?

### ISSUE THREAD

**Issue by evbo** [dtolnay/thiserror#308]
I use AWS step functions to report errors and they need the full error message, including source details.

How can I add the `source()` to the displayed error? Could it be as simple as?:

```rust
#[derive(Error, Debug)]
pub enum MyError {
    #[error("Reqwest failed: {0:?} caused by: {:?}", self.0.source())]
    ReqwestError(#[from] reqwest::Error)
}
```

**Comment by dtolnay** [comment]
Sources should **not** be part of the default Display representation of an error (`"{}"`).

To print an error together with chain of sources, you would need to do something like what's shown in https://docs.rs/anyhow/1.0.86/anyhow/struct.Error.html#display-representations.

**Comment by evbo** [comment]
@dtolnay Is there any way possible using thiserror to just jam the `source` into the default display? 

I get that anyhow supports it, but just to get this one feature to work seems overkill bringing in another dependency.
