### ISSUE TITLE
Error propagation macro

### ISSUE THREAD

**Issue by sander-willems-bruker** [dtolnay/thiserror#311]
Hi all,

I am still quite new to Rust and still figuring out how to quickly develop correct, safe, performant and idiomatic rust code. During my development, I noticed I kept repeating the same boilerplate code over and over when I want to propagate errors, and when posing the issue to AI tools it proposed to implement following macro which seems to work quite well for my use case:
```rust
#[macro_export]
macro_rules! propagated_error_enum {
    ($name:ident, $($variant:ident),+) => {
        #[derive(Debug, thiserror::Error)]
        pub enum $name {
            $(
                #[error(transparent)]
                $variant(#[from] $variant),
            )+
        }
    };
}
```
Good practice teaches me AI-generated code can be useful, but in the end I am aware of plenty AI pitfalls and value expert opinions far more. As such, what do you guys think about this macro; is it correct, safe, simple, idiomatic, useful, ...?

Best,
Sander

**Comment by dtolnay** [comment]
Your question would be more appropriate for one of the resources shown in https://www.rust-lang.org/community.
