### ISSUE TITLE
Nightly requirement on backtraces

### ISSUE THREAD

**Issue by arcanis** [dtolnay/thiserror#314]
I noticed that `std::backtrace::Backtrace` was standardized, but `thiserror` seems to still require a nightly build and special feature to have support for `#[backtrace]` - is that expected? Is there a way to have a (prehaps just basic) support for stacktrace captures from within the `From` implementation using only stable features?

**Comment by dtolnay** [comment]
It is expected. Only the Backtrace type has been stabilized so far, not backtraces in the Error trait.

Storing backtraces in From without exposing them in the Error impl is not supported, but you can write your own From impls or use a different From derive macro to do this.
