### ISSUE TITLE
Support no-std

### ISSUE THREAD

**Issue by kayabaNerve** [dtolnay/thiserror#318]
core::error::Error was stabilized in 1.81, which just released.

I'd comment on the existing issue yet noted https://github.com/dtolnay/thiserror/issues/196#issuecomment-1636066787.

**Comment by SyntheticBird45** [comment]
I support the addition of this feature. `thiserror` is a blessed crate I would appreciate using in my `#![no_std]` projects

**Comment by Systemcluster** [comment]
There is an open pull request: #304

**Comment by robamu** [comment]
I also strongly support this and would also very much appreciate this in my `no_std` crates :+1:

**Comment by mchodzikiewicz** [comment]
having this would be a huge deal for entire embedded community
