### ISSUE TITLE
License files updates

### ISSUE THREAD

**Issue by andygup** [dtolnay/thiserror#319]
@dtolnay can you please add a year and copyright holder name to both the Apache 2.0 and MIT license files? That would be much appreciated.

References: 
* https://www.apache.org/licenses/LICENSE-2.0#apply
* https://fossa.com/blog/open-source-licenses-101-mit-license/ > Requirements

**Comment by dtolnay** [comment]
It is my understanding that this is not a requirement of correctly using either of those licenses.

**Comment by andygup** [comment]
@mmgeorge yes, that's my interpretation, as well. 

The copyright requirements is spelled out in the license wording, for example in Apache 2.0: "Licensor" shall mean the copyright owner or entity authorized by the copyright owner that is granting the License.

**Comment by dtolnay** [comment]
Your lawyers' interpretation is extremely nonstandard.

If I were to add a file called COPYRIGHT containing the text "Copyright various contributors", does that unblock you?

**Comment by mmgeorge** [comment]
Hi @dtolnay the decision was made to remove this, & I'm currently going through the code now. Feel free to close. Thanks for looking though!
