### ISSUE TITLE
Is it possible (or intended) to use an enum member as a source?

### ISSUE THREAD

**Issue by urschrei** [dtolnay/thiserror#32]
It isn't possible to use an existing enum member as a `#[source]`, in situations where you want to accumulate or transform errors that have been defined in the same crate, so you can drill down using `source()`:

    use thiserror::Error;

    #[derive(Error, Debug)]
    pub enum SomeError {
        #[error("Foo")]
        FooError,
        #[error("Bar")]
        Test(#[source] crate::SomeError)
    }

As this leads to `error[E0072]: recursive type SomeError has infinite size`. It can be fixed by boxing `crate::SomeError`, but is this a terrible idea / an intended limitation / am I missing something obvious?

**Comment by dtolnay** [comment]
Your type is asking for the layout of some part of itself to be identical to the layout of the whole thing, which isn't meaningful.

```
|-------||-----------------------|
 \ tag /  \_     SomeError     _/

 \_         SomeError          _/
```

**Comment by urschrei** [comment]
Ah, sorry, I didn't mean to imply that this was a `thiserror`-specific issue, only that if you hand-roll your Error impls you're free to use them as sources for one another. Is the simplest solution to define different enums if you want to do that?

**Comment by dtolnay** [comment]
Could you show how you would want to do this if you were handrolling the Error impls?

**Comment by urschrei** [comment]
Slightly contrived, but: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d103b4ce96051916a93b4753011a37be

**Comment by dtolnay** [comment]
Doesn't that same thing work already with thiserror?

```rust
use thiserror::Error;

#[derive(Error, Debug)]
#[error("Couldn't convert tuple")]
pub struct TFError {
    #[source]
    coorderror: CoordError,
}

#[derive(Error, Debug)]
#[error("Coordinate conversion error")]
pub struct CoordError;
```

**Comment by urschrei** [comment]
Ah, that's what I mean by "define different enums if you want to do that", so, yes!
