### ISSUE TITLE
`#![error(transparent)]` doesn't really work for one of the reccommended usecases

### ISSUE THREAD

**Issue by lolbinarycat** [dtolnay/thiserror#324]
the docs suggest using this to hide internals, but `From` isn't transitive, so `?` won't be able to convert from the double nested error type to the outer type.

**Comment by dtolnay** [comment]
I am not confident what you mean by "From isn't transitive", but you can add your own From impls on either type as needed. If the goal is hiding internals, it's not clear that you would want publicly accessible From impls that are coupled to the internals.

**Comment by lolbinarycat** [comment]
my issue is that using that method makes `?` not work.  i suppose i'm supposed to have a whole facade layer to all my apis?
