### ISSUE TITLE
Ident cannot contain number. Is that intentional?

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [dtolnay/thiserror#34]
https://github.com/dtolnay/thiserror/blob/f1bf89d286a7d0d700db449d7cdf13af3d0ed67f/impl/src/fmt.rs#L66

This will cut off indentifier at the first occurrance of number if I get it right.
The identifier like `"{a1b}"` would be cut as `"a”` and `“{1b}”` which will just not work.

Is that intentional?

**Comment by dtolnay** [comment]
Thanks, not intentional. I released 1.0.3 with a fix.
