### ISSUE TITLE
Add defmt support

### ISSUE THREAD

**Issue by darkwater** [dtolnay/thiserror#374]
Now that Error is in core and no_std is supported, it might be nice to support [`defmt`](https://defmt.ferrous-systems.com/) as alternative to `core::fmt::Display`. It's popular for embedded Rust, and works by embedding strings in the ELF binary and essentially sending string indices instead of the entire string over the wire. Not only is this more efficient, it's also preferrable to not have `core::fmt` in the binary at all, because it can add many kilobytes to the total binary size.

The API is similar to `core::fmt`, with some limitations. I'd guess the user API could stay the same, except for some features that wouldn't be possible with defmt.

**Comment by dtolnay** [comment]
I do not understand this suggestion because core::error::Error requires an implementation of core::fmt::Display on the same type. You are not going to "not have `core::fmt` in the binary at all".

If you can elaborate exactly what code you are asking for `derive(Error)` to expand to then I can take another look.

**Comment by flippette** [comment]
> If you can elaborate exactly what code you are asking for `derive(Error)` to expand to then I can take another look.

I hope I can change your mind :')

This code:

```rust
use thiserror::Error;

#[allow(dead_code)]
#[derive(Debug, Error)]
enum Error {
    #[error("empty error")]
    Empty,
    
    #[error("display format: {0}")]
    Display(u16),
    
    #[error("debug format: {0:?}")]
    Debug(String),
    
    #[error("struct format: {a:?}, {b}")]
    Struct {
        a: String,
        b: u32,
    },
    
    #[error("array format: {0:?}")]
    Array([u16; 8]),
}
```

currently expands to this (trimmed to just the `Display` impl):

```rust
#[allow(unused_qualifications)]
#[automatically_derived]
impl ::core::fmt::Display for Error {
    fn fmt(&self, __formatter: &mut ::core::fmt::Formatter)
        -> ::core::fmt::Result {
        use ::thiserror::__private::AsDisplay as _;

        #[allow(unused_variables, deprecated, clippy ::
        used_underscore_binding)]
        match self {
            Error::Empty {} => __formatter.write_str("empty error"),
            Error::Display(_0) =>
                match (_0.as_display(),) {
                    (__display0,) =>
                        __formatter.write_fmt(format_args!("display format: {0}",
                                __display0)),
                },
            Error::Debug(_0) =>
                match (_0,) {
                    (__field0,) =>
                        __formatter.write_fmt(format_args!("debug format: {0:?}",
                                __field0)),
                },
            Error::Struct { a, b } =>
                match (a, b.as_display()) {
                    (__field_a, __display_b) =>
                        __formatter.write_fmt(format_args!("struct format: {0:?}, {1}",
                                __field_a, __display_b)),
                },
            Error::Array(_0) =>
                match (_0,) {
                    (__field0,) =>
                        __formatter.write_fmt(format_args!("array format: {0:?}",
                                __field0)),
                },
        }
    }
}
```

Which is this in cleaned up, human Rust:

```rust
impl core::fmt::Display for Error {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        match self {
            Error::Empty => core::write!(f, "empty error"),
            Error::Display(num) => core::write!(f, "display format: {0}", msg),
            Error::Debug(msg) => core::write!(f, "debug format: {0:?}", msg),
            Error::Struct { a, b } => core::write!(f, "struct format: {0:?} {1}", a, b),
            Error::Array(arr) => core::write!(f, "array format: {0:?}", arr),
        }
    }
}
```

The format strings used in `defmt` are a slightly different, so maybe it can expand to this:

```rust
impl defmt::Format for Error {
    fn format(&self, f: defmt::Formatter<'_>) {
        match self {
            Error::Empty => defmt::write!(f, "empty error"),
            Error::Display(num) => defmt::write!(f, "display format: {0}", msg),

            // see <https://defmt.ferrous-systems.com/hints> for a list of supported hints
            Error::Debug(msg) => defmt::write!(f, "debug format: {0:?}", msg),
            Error::Struct { a, b } => defmt::write!(f, "struct format: {0:?} {1}", a, b),
            Error::Array(arr) => defmt::write!(f, "array format: {0:?}", arr),
        }
    }
}

```

`defmt` also supports [type hints](https://defmt.ferrous-systems.com/macros#type-and-display-hints) for efficiency reasons, so it would be nice to have this:

```rust
impl defmt::Format for Error {
    fn format(&self, f: defmt::Formatter<'_>) {
        match self {
            Error::Empty => defmt::write!(f, "empty error"),
            Error::Display(msg) => defmt::write!(f, "display format: {0=u16}", msg),

            // see <https://defmt.ferrous-systems.com/hints> for a list of supported hints
            Error::Debug(msg) => defmt::write!(f, "debug format: {0=str:?}", msg),
            Error::Struct { a, b } => defmt::write!(f, "struct format: {0=str:?} {1=u32}", a, b),

            // in the special case that `arr` is of type `[u8; _]` there's a special type hint,
            // otherwise only `=[?; _]` is accepted
            Error::Array(arr) => defmt::write!(f, "array format: {0=[?; 8]:?}", arr),
        }
    }
}
```

> You are not going to "not have core::fmt in the binary at all".

Sure you can (if you enable `-Zbuild-std-features=panic_immediate_abort`, that is):

```rust
apple2040 on  main [?] ❯ cargo bloat -n 128 2>/dev/null | rg fmt | rg -v defmt | wc -l
0
```

**Comment by dtolnay** [comment]
Is the suggestion that `derive(Error)` should not emit an `Error` impl, only a `defmt::Format` impl? If so, what you want is a `defmt::Format` derive, not an `Error` derive.

**Comment by flippette** [comment]
Since `Error: Display`, `thiserror` should still emit a `Display` impl anyway, but as long as you don't panic in firmware code, maybe dead code elimination can still work?

**Comment by flippette** [comment]
Ah, okay, I realize `Result::E: ?Error`

**Comment by dtolnay** [comment]
If you are banking on the `Error` (and `Display`) impl to get eliminated as dead, what you want is a `defmt::Format` derive.

**Comment by oleid** [comment]
> If you are banking on the `Error` (and `Display`) impl to get eliminated as dead, what you want is a `defmt::Format` derive.

I just stumbled across the same thing.
Would it make sense to open the issue again?
