### ISSUE TITLE
`derive(Error)` hangs on invalid input in `#[error]` helper attribute

### ISSUE THREAD

**Issue by zachs18** [dtolnay/thiserror#381]
```rs
use thiserror::Error;

#[derive(Error, Debug)]
pub enum ArgError {
    #[error("".yellow)]
    InvalidUrl,
}
```

 causes the compiler to hang.
 
Specifically, it seems like this `while` loop https://github.com/dtolnay/thiserror/blob/master/impl/src/fmt.rs#L218-L229 is infinite if the input is not as expected; the `if` statement is skipped and `input` never changes, so the `if` statement is forever skipped.

**Comment by dtolnay** [comment]
Fixed in 2.0.2.
