### ISSUE TITLE
Feature request: allow adding `inline` to the generated `from` impls

### ISSUE THREAD

**Issue by V0ldek** [dtolnay/thiserror#403]
I have the [`missing_inline_in_public_items`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_inline_in_public_items) lint enabled in my crate and I'm currently upping `thiserror` to 2.0. For some reason, the `From` impls from `thiserror` start tripping up this lint after the upgrade (see e.g. [this action](https://github.com/rsonquery/rsonpath/actions/runs/12446905151/job/34749812539?pr=614)). I don't know why the upgrade causes it, since as far as I can see the `From` impls were never inline in 1.0 either, but that's a secondary issue.

It'd be nice if it was possible to add an `inline` attribute to the `#[from]` specifier. I could see two ways for this:

1. Just allow `#[from(inline)]` which slaps `#[inline]` onto the generated impl.
2. Allow a more generic mechanism where this:

```rust
#[derive(Error)]
enum MyError {
  IO(#[from] #[inline] #[deprecated("Reason")] #[any_other_attr("with", "args")] std::io::Error)
}
```

results in this impl:

```rust
impl From<std::io::Error> for MyError {
    #[inline]
    #[deprecated("Reason")]
    #[any_other_attr("with", "args")]
    fn from(value: std::io::Error) -> Self {
        Self::IO(value)
    }
}
```

I'm not familiar enough with macros to figure out how hard the second approach would be, though.

**Comment by dtolnay** [comment]
Please try 2.0.9. It should behave equivalently to 1.x in regard to missing_inline_in_public_items.

**Comment by V0ldek** [comment]
> should behave equivalently to 1.x in regard to missing_inline_in_public_items.

Indeed it does, thank you.

What about the ability to mark the generated functions as `#[inline]` somehow?

**Comment by dtolnay** [comment]
I think that is almost certainly misguided. Those functions are only called on the error codepath and not on the usually performance sensitive happy path.
