### ISSUE TITLE
Supporting doc comment syntax as an alternative to `#[error]`

### ISSUE THREAD

**Issue by bstrie** [dtolnay/thiserror#44]
After taking a look at displaydoc (https://github.com/yaahc/displaydoc), which I believe is based upon code from thiserror, I'm somewhat enamored at its use of doc comment syntax rather than a custom attribute and I'm curious whether you'd consider allowing the same for thiserror (especially since you already go to lengths to allow users to not have to manually use the `source` and `backtrace` custom attributes).

Using the example in the documentation for comparison, the before:
```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum DataStoreError {
    #[error("data store disconnected")]
    Disconnect(#[from] io::Error),
    #[error("the data for key `{0}` is not available")]
    Redaction(String),
    #[error("invalid header (expected {expected:?}, found {found:?})")]
    InvalidHeader {
        expected: String,
        found: String,
    },
    #[error("unknown data store error")]
    Unknown,
}
```
...and the after:
```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum DataStoreError {
    /// data store disconnected
    Disconnect(#[from] io::Error),
    /// the data for key `{0}` is not available
    Redaction(String),
    /// invalid header (expected {expected:?}, found {found:?})
    InvalidHeader {
        expected: String,
        found: String,
    },
    /// unknown data store error
    Unknown,
}
```

**Comment by dtolnay** [comment]
I am not interested in building this into thiserror, but you can use displaydoc's Display derive with thiserror's Error derive.

**Comment by bstrie** [comment]
Sure, I was just curious if I could avoid having two dependencies that seem to share the exact same code. :P I'll close this then.

**Comment by djahandarie** [comment]
@dtolnay Just curious, have you investigated error & doc integration the other way around -- i.e, having RustDoc pick up on the error derive and integrating that info into the docs somehow?

Or do you think just using both libraries at the same time is the best approach?
