### ISSUE TITLE
A field with a type named `Backtrace` that is not `std::backtrace::Backtrace` causes an error even without `#[from]`

### ISSUE THREAD

**Issue by jplatte** [dtolnay/thiserror#45]
The title pretty much says it all. Since `std::backtrace` is still unstable, I'm using the backtrace crate. However, I currently have to rename `backtrace::Backtrace` because as soon as I refer to it as `Backtrace`, `std::backtrace::Backtrace` is apparently referenced in the generated code, even without any `#[from]` attributes.

**Comment by jplatte** [comment]
@dtolnay would you accept a PR that fixes this?

**Comment by dtolnay** [comment]
I would be interested in a PR but I won't necessarily accept one. Do you have an idea of how you would want the fix to work?

**Comment by jplatte** [comment]
I don't yet, and also haven't looked at what code is generated that causes this yet either. Maybe I'm missing something, but from the docs it looks like `std::backtrace::Backtrace` should only be relevant in conjunction with `#[from] (or `#[source]`).

**Comment by jplatte** [comment]
I see, this was just me out knowing much about the Error trait + either thiserror's docs were previously a bit unclear about backtraces or I just misread them. They are clear now though. 

The only improvement I can still see is emitting an error when a Backtrace field is present but the compiler used is a non-nightly where the backtrace method is not yet usable. That's not what this issue is about though so I'll close it.

**Comment by ngugc** [comment]
So is there a way to use the traceback function on a stable channel?

**Comment by EvanCarroll** [comment]
I'm getting this error still. It's not clean in the docs why something like this doesn't work..

```
      #[error("Could not parse listing page [Listing: {listing_id:?}] {backtrace:#?}")]
      ListingParseError { listing_id: u64, backtrace: Backtrace },
```
