### ISSUE TITLE
as_dyn_error compilation error

### ISSUE THREAD

**Issue by U007D** [dtolnay/thiserror#51]
I searched through the documentation for any reference to `as_dyn_error` but nothing came back.

```rust
use thiserror::Error;

mod msg {
    pub const ERR_ARG_NOT_CONVERTIBLE_TO_UTF_8: &str =
        "Error: supplied command-line argument not convertible to UTF-8";
}

pub enum Error {
    #[error("{}: {:?}", msg::ERR_ARG_NOT_CONVERTIBLE_TO_UTF_8, 0)]
    ArgNotConvertibleToUtf8(#[from] std::ffi::OsString),
}
```
yields:
```
error[E0599]: no method named `as_dyn_error` found for type `&std::ffi::OsString` in the current scope
 --> src/error.rs:6:17
  |
6 | #[derive(Debug, Error)]
  |                 ^^^^^ method not found in `&std::ffi::OsString`
  |
  = note: the method `as_dyn_error` exists but the following trait bounds were not satisfied:
          `&std::ffi::OsString : thiserror::aserror::AsDynError`
          `std::ffi::OsStr : thiserror::aserror::AsDynError`
          `std::ffi::OsString : thiserror::aserror::AsDynError`

error: could not compile `foo`.
```
yet commenting out the `#[from]` attribute and creating my own `From` impl:
```rust
impl From<std::ffi::OsString> for Error {
    fn from(err: OsString) -> Self {
        Self::ArgNotConvertibleToUtf8(err)
    }
}
```
and everything compiles fine.  Am I missing something obvious?

**Comment by dtolnay** [comment]
The `#[from]` attribute is not a general-purpose std::convert::From derive. It is specifically for source conversions. Sources aren't allowed to be an arbitrary type, they must implement std::error::Error which OsString does not. https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.source

It has to do with this part of the readme:

> The `#[from]` attribute always implies that the same field is `#[source]`, so you don't ever need to specify both attributes.

Any `From` impl that doesn't have to do with Error::source isn't going to be related to the Error trait at all, so we shouldn't be using a derive(Error) to emit those impls.

**Comment by U007D** [comment]
Thank you, David, that makes sense.
