### ISSUE TITLE
Some kind of from attribute without Backtrace

### ISSUE THREAD

**Issue by Luro02** [dtolnay/thiserror#56]
I mean what's the point of Backtrace? If something crashes you can always use `RUST_BACKTRACE=1 cargo run` and see the entire backtrace.

Therefore it'd be nice to be able to derive a from impl, but without the requirement for a Backtrace field.

**Comment by dtolnay** [comment]
A backtrace field is not required. https://github.com/dtolnay/thiserror#example shows an example of #\[from\] without a backtrace field.
