### ISSUE TITLE
Support custom string for None/Some(T)

### ISSUE THREAD

**Issue by Nokel81** [dtolnay/thiserror#59]
It would be very useful to be able to support specialized display strings for when an argument of an enum is of type `Option<T>` and is the variant `None`. This would also remove the `Some(...)` from the display on the `Some` variant.

**Comment by dtolnay** [comment]
Could you show an example of what you would like to be able to write?

Nothing in thiserror automatically puts "None" or "Some" into the display string, that must be from using {:?} on the field in your format string.

**Comment by Nokel81** [comment]
I guess I meant that for the type `Option<T: Display>` you would provided two strings, one for `Some(t)` which would be the same as `{}` for the `T` and the other not having one at all.

Example:

```rust
#[derive(Error)]
pub enum MyError {
    #[error(
        1.Some:"a variant error occurred with {1}: {0}"; 
        1.None:"there was an empty variant error: {0}"
    )]
    Variant(String, Option<usize>)
}
```

**Comment by dtolnay** [comment]
I would prefer not to build fancier support for this into thiserror. For now you can handwrite the Display impl, or make this work using the existing features depending on your preference.

```rust
#[derive(Error, Debug)]
pub enum MyError {
    Variant(String, Option<usize>)
}

impl Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            MyError::Variant(a, Some(b)) => {
                write!(f, "a variant error occurred with {}: {}", b, a)
            }
            MyError::Variant(a, None) => {
                write!(f, "there was an empty variant error: {}", a)
            } 
        }
    }
}
```

```rust
#[derive(Error, Debug)]
pub enum MyError {
    #[error("{}: {0}", match _1 {
        Some(n) => format!("a variant error occured with {}", n),
        None => format!("there was an empty variant error"),
    })]
    Variant(String, Option<usize>),
}
```

**Comment by Nokel81** [comment]
Would it be possible to get the second one into the documentation? I didn't even know that existed.

**Comment by dtolnay** [comment]
I believe this is largely covered by the third bullet of https://github.com/dtolnay/thiserror/tree/ff9524e1fd65fc49cfe905e9456c255e470fb239#details which mentions that format arguments may be arbitrary expressions, with multiple examples.

The use of `_1` instead of `.1` is a temporary limitation until #54 is fixed.

**Comment by Nokel81** [comment]
Excellent, thanks.
