### ISSUE TITLE
the trait `std::convert::From<std::convert::Infallible>` is not implemented for `MyOwnError`

### ISSUE THREAD

**Issue by bestouff** [dtolnay/thiserror#62]
I'm generating code which can result in this error:
```
the trait `std::convert::From<std::convert::Infallible>` is not implemented for `MyOwnError`
```
This is because (of course) I have a function which can't fail (`from_str()` actually) but try to convert that to a `Result<_, MyOwnError>` via a question mark.  
For now I have implemented [this workaround](https://github.com/rust-lang-nursery/error-chain/issues/229#issuecomment-333406310) manually:
```rust
impl From<Infallible> for MyOwnError {
    fn from(_: Infallible) -> Self {
        unreachable!()
    }
}
```
but I'd prefer if it could be done automagically.

**Comment by dtolnay** [comment]
I would prefer not to build anything for this into thiserror. That error will be solved by adding `impl<T> From<!> to T` in the standard library (https://github.com/rust-lang/rust/issues/64715). Until then, the handwritten impl is fine or you could look for a `From` derive macro which could generate it.

**Comment by leighmcculloch** [comment]
It appears `impl<T> From<!> to T` has been marked as permanent unstable just recently: https://github.com/rust-lang/rust/issues/64715#event-6858802725. Could this issue be reconsidered given that?

**Comment by evbo** [comment]
I too am hitting this when I implement `From` and try to use the blanket implementation of `TryFrom`

I'm not so sure my function "can't fail" as I am using `try_into()` to anticipate when it may fail. But in certain contexts it shouldn't fail, and so I also need `into()` 

What is the proposed workaround doing exactly? I am so confused and hate just copying and pasting this. Can anyone clarify?
