### ISSUE TITLE
Please support `#[display("...")]` as a synonym for `#[error("...")]`

### ISSUE THREAD

**Issue by joshtriplett** [dtolnay/thiserror#65]
The `#[error("...")]` message defines how the type implements `Display`. It might make sense to call that `#[display("...")]` instead, with an eye towards supporting it as a separate `derive(Display)` in the future.

Inspired by the thread at https://internals.rust-lang.org/t/deriving-error/11894/ .

**Comment by dtolnay** [comment]
This is already supported.

```rust
use thiserror::Error;
use whatever_crate::Display;

#[derive(Error, Display, Debug)]
#[display("...")]
struct Error;
```

**Comment by joshtriplett** [comment]
...I didn't realize this. Thank you!

https://docs.rs/thiserror/1.0.11/thiserror/derive.Error.html doesn't seem to document that; it doesn't list `#[display]`.

**Comment by dtolnay** [comment]
Well it would be documented on https://docs.rs/parse-display-derive/0.1.1/parse_display_derive/derive.Display.html or https://docs.rs/kg-display-derive/0.1.1/kg_display_derive/derive.Display.html or whichever Display derive is being used.

**Comment by joshtriplett** [comment]
Ah, sorry, I misunderstood. I thought you were suggesting that thiserror supported `#[display]`.

I was asking if you would consider making `thiserror` support the `#[display]` attribute as an alias for `#[error]`.

**Comment by dtolnay** [comment]
> with an eye towards supporting it as a separate `derive(Display)` in the future.

As I understand it, the thing you are asking for is for `derive(Error)` to accept `#[display]` attributes as a halfway point toward having those broken out to a separate `derive(Display)` in the future.

But that isn't a future thing, using an independent `derive(Display)` is already supported today. Isn't putting `display` attributes into `derive(Error)` a step in the wrong direction?

```
----------------------------------------------------------------------------------->
derive(Error)    derive(Error)                       derive(Error, Display)
#[error(...)]    #[error(...)] or #[display(...)]    #[error(...)] + #[display(...)]

     ^ where you thought we are

                      ^ what you are asking for

                                                          ^ where we actually are
```
