### ISSUE TITLE
Integration test cases

### ISSUE THREAD

**Issue by pythondude325** [dtolnay/thiserror#66]
I work on rcc, a c compiler in rust. Thiserror has been very valuable in the development of the rcc. Over time we have noticed some very minor issues with the macro and I was wondering if you would be interested in using our error types as an integration test. The [`src/data/error.rs`](https://github.com/jyn514/rcc/blob/master/src/data/error.rs) file in the rcc repository contains large error types using the thiserror derive macro.

**Comment by jyn514** [comment]
For context, we noticed that `1.0.9` doesn't work with the latest version of `rcc`, even though `1.0.10` and up still work. I thought having `error.rs` might be helpful in avoiding regressions.

**Comment by dtolnay** [comment]
Thanks!
