### ISSUE TITLE
backtrace() should prefer the source's backtrace if it has one

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/thiserror#7]
```rust
#[derive(Error, Debug)]
pub struct Error {
    #[source]
    source: anyhow::Error,
    backtrace: Backtrace,
}
```

Currently the generated `backtrace()` method would just return `Some(&self.backtrace)`. Instead it should be returning `Some(self.source.backtrace().unwrap_or(&self.backtrace))`. The lower-level error will tend to have a deeper more relevant backtrace.

Note: I am not confident about this. Which behavior is the right one?

Separately, we should return source backtraces if self doesn't contain its own backtrace, which we don't currently do. `self.source.backtrace()` in the following case.

```rust
#[derive(Error, Debug)]
pub struct Error {
    #[source]
    source: anyhow::Error,
}
```

**Comment by Jezza** [comment]
Yeah, source's backtrace should be more relevant.

Maybe a good idea would be an explicit `#[backtrace]`.  
Only needed if it's ambiguous, or even better, default to the source's backtrace, but emit a warning or something.  
That way nothing breaks, the users can still select the one they want, and we get better default backtraces.

**Comment by TyPR124** [comment]
What if the user launches a thread that might return an error, and they include that error as a source on the main thread? Would that produce two completely separate (but potentially equally important) backtraces?

If that is correct, I feel like hiding the outer backtrace may be a bad idea, especially as the inner backtrace would still be accessible through source.

**Comment by mathstuf** [comment]
An explicit `#[backtrace]` could elevate its precedence over the `source` backtrace.
