### ISSUE TITLE
Document that #[error] attribute works for whole structs too

### ISSUE THREAD

**Issue by Kixunil** [dtolnay/thiserror#70]
I just needed to derive primitive `Display` for a ZST and since I was already using `thiserror` I immediately started to search for solution. It's not documented, but I had a strong suspicion and found #3.

Please document it, so it's easier to find. A single phrase or an example would be sufficient.

**Comment by dtolnay** [comment]
The very first sentence in the readme and rustdoc about #\[error\] is:

> A `Display` impl is generated for your error if you provide `#[error("...")]` messages on the struct or each variant of your enum

so I think this already covers that it works for structs.

**Comment by Kixunil** [comment]
Ah, yeah, I think that the way it speaks about struct and variants with plural confused me, sorry. Maybe something like "if you provide `#[error("...")]` message on the whole struct or each variant of an enum" would be cleaner, but I wouldn't be surprised if it's just me being confused.
