### ISSUE TITLE
error(transparent) on structures

### ISSUE THREAD

**Issue by Ekleog** [dtolnay/thiserror#80]
Hello,

I think I haven't had yet the occasion to thank you for `thiserror` (as well as a lot of other crates actually), so here it is: thank you! And sorry for not having had issues with your crates earlier, which would have allowed me to thank you without just spamming :stuck_out_tongue: 

I recently hit a limitation of `thiserror`: sometimes, I just want to hide an error type from a sub-library, and re-export it under another name, so that the implementation details don't leak.

So I originally tried this:
```rust
#[derive(Debug, thiserror::Error)]
struct E(#[error(transparent)] std::io::Error);
```
However, it looks like this doesn't implement `Display` for `E`.

On the other hand, this works perfectly:
```rust
#[derive(Debug, thiserror::Error)]
enum E { #[error(transparent)] Foo(std::io::Error) }
```
But then, it leaks the implementation detail of the inner error type.

Do you think it'd make sense to have `#[error(transparent)]` work on structs? Or maybe it'd be a bad idea anyway for reasons I can't think of right now?

**Comment by dtolnay** [comment]
The transparent attr goes on an enum variant or struct, not on an individual field. I think this does what you want:

```rust
#[derive(Error, Debug)]
#[error(transparent)]
struct E(std::io::Error);
```

**Comment by Ekleog** [comment]
Looks like that's what I was looking for indeed! I guess a diagnostic for https://github.com/dtolnay/thiserror/issues/81 would probably have avoided that error, closing here :)

Thank you!
