### ISSUE TITLE
Gathering errors into one variant

### ISSUE THREAD

**Issue by Dushistov** [dtolnay/thiserror#97]
With quick_error I can gather several variant into one enum variant,
see  `UnderlyingDbError` in code bellow.

```
quick_error! {
    #[derive(Debug, Clone)]
    pub enum NavLoggerError {
        UnderlyingDbError(err: String) {
            display("UnderlyingDbError: {}", err)
            from(err: rusqlite::Error) -> (format!("rusqlite::Error: {}", err))
            from(err: bincode::Error) -> (format!("bincode::Error: {}", err))
            from(err: std::io::Error) -> (format!("std::io::Error: {}", err))
            from(err: FromSqlError) -> (format!("rusqlite::FromSqlError: {}", err))
        }
        SchemaError(err: String) {
            display("SchemaError: {}", err)
        }
        InvalidObject(err: String) {
            display("InvalidObject: {}", err)
        }
     }
}
```

To accomplish the same with `thiserror` I can only use two types: 
```
#[derive(Debug, Error)]
pub enum NavLoggerError {
    #[error(transparent)]
    UnderlyingDbError(#[from] UnderlyingDbError),
    #[error("NavLoggerError: Schema error: {0}")]
    SchemaError(String),
    #[error("NavLoggerError: Invalid object: {0}")]
    InvalidObject(String),
}

#[derive(Debug, Error)]
pub enum UnderlyingDbError {
    #[error(transparent)]
    Rusqlite(#[from] rusqlite::Error),
    #[error(transparent)]
    Bincode(#[from] bincode::Error),
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    FromSqlError(#[from] FromSqlError),
}
```

but with two types I can not use `?` directly,
I have to use `map_err` because of conversation requires two conversation, instead of one.

So it would be nice to have:
1. several `#[from` in one variant
2. Way to use `#[from` to convert to `String`

**Comment by ctron** [comment]
I just ran into the same issue. I am not sure handwriting is the right resolution here, as thiserror is about to make it easier to handle errors.

In my case I have:

~~~rust
pub enum ErrorTypeA {
  Reason1, Reason2, Reason3, // all with #[from]
}

pub enum ErrorTypeB {
  TypeA(ErrorTypeA),
  MyError,
}

pub enum ErrorTypeC {
  TypeA(ErrorTypeA),
  MyOtherError,
}
~~~

Having to handwrite things would mean, that I have to re-create all `From`s for `ErrorTypeB` and `ErrorTypeC`. And would I add another `ErrorTypeD` I would need to re-do everything again.

Maybe there is a way around this with some other crate. But I think this is a reasonable use case, and there should at least be an example on how to handle this with `thiserror`.

Rust error handling is hard enough. I think that "thiserror" is a huge improvement, so maybe it could be improved a bit more.

**Comment by ctron** [comment]
Just thinking about what I would like to write, using `thiserror`, not sure this is technically possible:

~~~rust
#[derive(Debug, Error)]
pub enum ErrorTypeA {
  #[error("Failed")]
  Reason1(#[from] Source1),
  #[error("Failed too")]
  Reason1(#[from] Source2),
}

#[derive(Debug,Error)]
pub enum ErrorTypeB {
  #[error("Failed again")]
  ReasonA(#[from(inherit)] ErrorTypeA),
  #[error("My custom error")]
   MyError,
}
~~~

So thiserror would create:

~~~
from Source1 -> ErrorTypeA::Reason1
from Source2 -> ErrorTypeA::Reason2

from ErrorTypeA -> ErrorTypeB::ReasonA
from Source1 -> ErrorTypeB::ReasonA(ErrorTypeA::Reason1)
from Source2 -> ErrorTypeB::ReasonA(ErrorTypeA::Reason2)
~~~

Using `inherit` would require the target to be a `thiserror` too.
